<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ThemeCssExporter</RootNamespace>
    <AssemblyName>ThemeCssExporter</AssemblyName>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="C:\Users\SuperComp\Documents\Blazor\SuperUI.Blazor\SuperUI\SuperUI.csproj" />
  </ItemGroup>
</Project>
