using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.JSInterop;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text;
using SuperUI.Enums;
using SuperUI.Base.ComponentBases;
using SuperUI.Base.Utilities;
using SuperUI.Base.Utilities;

namespace SuperUI.Components;

/// <summary>A lightweight table component with sorting, pagination, selection, column resize/reorder, and export support.</summary>
/// <typeparam name="TItem">The type of data items displayed in the table.</typeparam>
public partial class SgTable<TItem> : SgComponentBase
{
    private readonly List<SgTableColumn<TItem>> _columns = new();
    private readonly List<SgTableColumn<TItem>> _autoGeneratedColumns = new();
    private bool _autoColumnsGenerated;
    private string? _searchText;
    private string? _sortColumnKey;
    private SgDataGridSortDirection _sortDirection = SgDataGridSortDirection.None;
    private int _pageNumber = 1;
    private readonly HashSet<TItem> _selectedItems = new();
    private bool _selectAll;
    private ElementReference _tableRef;
    private ElementReference _headerScrollRef;
    private ElementReference _bodyScrollRef;
    private IJSObjectReference? _jsModule;
    private CancellationTokenSource? _lifetimeCts;
    private Dictionary<string, double> _columnWidths = new();
    private string? _resizingColumn;
    private double _resizeStartX;
    private double _resizeStartWidth;
    private int? _draggedColumnIndex;
    private int? _dropTargetIndex;
    private List<SgTableHeaderGroup<TItem>> _headerGroups = new();
    private bool _showExportMenu;
    private ElementReference _exportRef;


    [Inject] private IJSRuntime JS { get; set; } = default!;
    [Inject] private SgJsModuleCache ModuleCache { get; set; } = default!;

    /// <summary>Whether to show a loading indicator.</summary>
    [Parameter] public bool Loading { get; set; }
    /// <summary>The data source items to display.</summary>
    [Parameter] public IEnumerable<TItem>? Items { get; set; }
    /// <summary>The content containing <see cref="SgTableColumn{TItem}"/> definitions.</summary>
    [Parameter] public RenderFragment? ChildContent { get; set; }
    /// <summary>The title displayed in the table toolbar.</summary>
    [Parameter] public string? Title { get; set; }
    /// <summary>Whether to show the search input in the toolbar.</summary>
    [Parameter] public bool ShowSearch { get; set; } = true;
    /// <summary>Placeholder text for the search input.</summary>
    [Parameter] public string? SearchPlaceholder { get; set; }
    /// <summary>The height of the table container.</summary>
    [Parameter] public string? Height { get; set; }
    /// <summary>The maximum height of the table container before scrolling.</summary>
    [Parameter] public string MaxHeight { get; set; } = "70vh";
    /// <summary>Whether the table should take the full width of its container.</summary>
    [Parameter] public bool FullWidth { get; set; }
    /// <summary>Text displayed when the table has no data.</summary>
    [Parameter] public string? EmptyText { get; set; }
    /// <summary>Whether to automatically generate columns from public properties of <typeparamref name="TItem"/>.</summary>
    [Parameter] public bool AutoGenerateColumns { get; set; }
    /// <summary>Optional function returning additional CSS class(es) for a row.</summary>
    [Parameter] public Func<TItem, string?>? RowClass { get; set; }
    /// <summary>Optional function returning inline CSS styles for a row.</summary>
    [Parameter] public Func<TItem, string?>? RowStyle { get; set; }
    /// <summary>Whether to show a row-number column.</summary>
    [Parameter] public bool ShowRowNumbers { get; set; }
    /// <summary>Whether to enable pagination.</summary>
    [Parameter] public bool EnablePaging { get; set; }
    /// <summary>The number of rows per page.</summary>
    [Parameter] public int PageSize { get; set; } = 20;
    /// <summary>Fired when the page size changes.</summary>
    [Parameter] public EventCallback<int> PageSizeChanged { get; set; }
    /// <summary>The current page number (1-based).</summary>
    [Parameter] public int PageNumber { get; set; } = 1;
    /// <summary>Fired when the page number changes.</summary>
    [Parameter] public EventCallback<int> PageNumberChanged { get; set; }
    /// <summary>Whether row selection is enabled.</summary>
    [Parameter] public bool AllowSelection { get; set; }
    /// <summary>Whether multiple rows can be selected at once.</summary>
    [Parameter] public bool AllowMultiSelect { get; set; }
    /// <summary>The currently selected items.</summary>
    [Parameter] public List<TItem> SelectedItems { get; set; } = new();
    /// <summary>Fired when the selected items change.</summary>
    [Parameter] public EventCallback<List<TItem>> SelectedItemsChanged { get; set; }
    /// <summary>Fired when a row is clicked.</summary>
    [Parameter] public EventCallback<TItem> RowClicked { get; set; }
    /// <summary>Fired when a row is double-clicked.</summary>
    [Parameter] public EventCallback<TItem> RowDoubleClicked { get; set; }
    /// <summary>Whether to show the export button in the toolbar.</summary>
    [Parameter] public bool ShowExport { get; set; }
    /// <summary>Whether to show the CSV export option.</summary>
    [Parameter] public bool ShowExportCsv { get; set; }
    /// <summary>Whether to show the Excel export option.</summary>
    [Parameter] public bool ShowExportExcel { get; set; }
    /// <summary>Whether to allow the user to change the page size.</summary>
    [Parameter] public bool AllowPageSizeChange { get; set; }
    /// <summary>Available page size options for the page size selector.</summary>
    [Parameter] public int[] PageSizeOptions { get; set; } = new[] { 10, 20, 50, 100 };
    /// <summary>Whether column widths can be resized by dragging the column borders.</summary>
    [Parameter] public bool AllowColumnResize { get; set; } = true;
    /// <summary>Whether columns can be reordered by drag-and-drop.</summary>
    [Parameter] public bool AllowColumnReorder { get; set; } = true;

    internal List<SgTableHeaderGroup<TItem>> HeaderGroups => _headerGroups;

    internal IReadOnlyList<SgTableColumn<TItem>> Columns
    {
        get
        {
            EnsureAutoGeneratedColumns();
            return _columns.Count > 0 ? _columns : _autoGeneratedColumns;
        }
    }

    private void EnsureAutoGeneratedColumns()
    {
        if (!AutoGenerateColumns) return;
        if (_autoColumnsGenerated) return;

        var itemType = typeof(TItem);
        var properties = itemType.GetProperties(BindingFlags.Public | BindingFlags.Instance);

        foreach (var prop in properties)
        {
            var displayAttr = prop.GetCustomAttribute<DisplayAttribute>();
            var displayNameAttr = prop.GetCustomAttribute<DisplayNameAttribute>();
            var browseAttr = prop.GetCustomAttribute<BrowsableAttribute>();

            if (browseAttr != null && !browseAttr.Browsable)
                continue;

            var title = displayAttr?.Name ?? displayNameAttr?.DisplayName ?? prop.Name;
            var key = prop.Name;

            var column = SgTableColumn<TItem>.CreateSynthetic(
                key,
                title,
                item => prop.GetValue(item),
                true,
                prop.PropertyType
            );

            _autoGeneratedColumns.Add(column);
        }

        _autoColumnsGenerated = true;
    }

    internal int TotalCount => FilteredAndSortedItems.Count();
    internal int TotalPages => Math.Max(1, (int)Math.Ceiling((double)TotalCount / PageSize));
    internal int CurrentPage
    {
        get
        {
            var page = PageNumber > 0 ? PageNumber : _pageNumber;
            return Math.Max(1, Math.Min(page, TotalPages));
        }
    }

    private async Task GoToPage(int page)
    {
        var targetPage = Math.Max(1, Math.Min(page, TotalPages));
        _pageNumber = targetPage;
        PageNumber = targetPage;
        
        if (PageNumberChanged.HasDelegate)
            await PageNumberChanged.InvokeAsync(targetPage);
            
        StateHasChanged();
    }

    internal List<TItem> FilteredAndSortedItems
    {
        get
        {
            if (Items == null) return new List<TItem>();
            var filtered = Items;
            if (!string.IsNullOrWhiteSpace(_searchText))
            {
                var search = _searchText.Trim().ToLowerInvariant();
                var cols = Columns;
                filtered = filtered.Where(item =>
                {
                    foreach (var col in cols)
                    {
                        var display = col.GetDisplay(item);
                        if (display.ToLowerInvariant().Contains(search))
                            return true;
                    }
                    return false;
                });
            }
            if (!string.IsNullOrWhiteSpace(_sortColumnKey))
            {
                var cols = Columns;
                var col = cols.FirstOrDefault(c => c.Key == _sortColumnKey);
                if (col != null)
                {
                    filtered =                     _sortDirection == SgDataGridSortDirection.Ascending
                        ? filtered.OrderBy(item => col.GetValue(item))
                        : filtered.OrderByDescending(item => col.GetValue(item));
                }
            }
            return filtered.ToList();
        }
    }
    internal IEnumerable<TItem> PagedItems
    {
        get
        {
            if (!EnablePaging) return FilteredAndSortedItems;
            return FilteredAndSortedItems.Skip((CurrentPage - 1) * PageSize).Take(PageSize);
        }
    }

    internal string EffectiveEmptyText => string.IsNullOrWhiteSpace(EmptyText) ? Localizer["Common_NoData"] : EmptyText!;

    internal void RegisterColumn(SgTableColumn<TItem> column)
    {
        if (!_columns.Contains(column))
        {
            _columns.Add(column);
            StateHasChanged();
        }
    }

    internal void UnregisterColumn(SgTableColumn<TItem> column)
    {
        _columns.Remove(column);
    }

    internal void RegisterHeaderGroup(SgTableHeaderGroup<TItem> group)
    {
        if (!_headerGroups.Contains(group))
        {
            _headerGroups.Add(group);
            StateHasChanged();
        }
    }

    internal void UnregisterHeaderGroup(SgTableHeaderGroup<TItem> group)
    {
        _headerGroups.Remove(group);
    }

    private async Task OnBodyScroll()
    {
        try
        {
            _jsModule ??= await JS.InvokeAsync<IJSObjectReference>(
                "import", "./_content/SuperUI/Components/Data/Table/SgTable.razor.js");
            await _jsModule.InvokeVoidAsync("syncHeaderScroll", _headerScrollRef, _bodyScrollRef);
        }
        catch (JSDisconnectedException) { }
        catch (TaskCanceledException) { }
        catch (ObjectDisposedException) { }
    }

    // Column resize
    private async Task OnResizeStart(MouseEventArgs e, string columnKey)
    {
        _resizingColumn = columnKey;
        _resizeStartX = e.ClientX;

        var col = Columns.FirstOrDefault(c => c.Key == columnKey);
        if (col != null)
        {
            if (_columnWidths.ContainsKey(columnKey))
            {
                _resizeStartWidth = _columnWidths[columnKey];
            }
            else if (!string.IsNullOrEmpty(col.Width) && col.Width.EndsWith("px"))
            {
                _resizeStartWidth = double.Parse(col.Width.Replace("px", ""));
            }
            else
            {
                _resizeStartWidth = 150; // default width
            }
        }

        _jsModule ??= await JS.InvokeAsync<IJSObjectReference>(
            "import", "./_content/SuperUI/Components/Data/Table/SgTable.razor.js");
        await _jsModule.InvokeVoidAsync("startColumnResize", _resizeStartX, _resizeStartWidth);
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (_resizingColumn != null)
        {
            try
            {
                _jsModule ??= await JS.InvokeAsync<IJSObjectReference>(
                    "import", "./_content/SuperUI/Components/Data/Table/SgTable.razor.js");
                var resizeEvent = await _jsModule.InvokeAsync<MouseEventArgs?>("pollResizeEvent");
                if (resizeEvent != null)
                {
                    var delta = resizeEvent.ClientX - _resizeStartX;
                    var newWidth = Math.Max(50, _resizeStartWidth + delta);
                    _columnWidths[_resizingColumn] = newWidth;
                    StateHasChanged();
                }

                var resizeEnd = await _jsModule.InvokeAsync<bool>("pollResizeEnd");
                if (resizeEnd)
                {
                    _resizingColumn = null;
                }
            }
            catch (JSDisconnectedException) { }
            catch (TaskCanceledException) { }
            catch (ObjectDisposedException) { }
        }
    }

    // Column drag and drop
    private void OnColumnDragStart(int columnIndex)
    {
        if (!AllowColumnReorder) return;
        _draggedColumnIndex = columnIndex;
        StateHasChanged();
    }

    private void OnColumnDragOver(int columnIndex)
    {
        if (!AllowColumnReorder || _draggedColumnIndex == null) return;
        if (_dropTargetIndex != columnIndex)
        {
            _dropTargetIndex = columnIndex;
            StateHasChanged();
        }
    }

    private void OnColumnDrop(int columnIndex)
    {
        if (!AllowColumnReorder || _draggedColumnIndex == null || _draggedColumnIndex == columnIndex)
        {
            _draggedColumnIndex = null;
            _dropTargetIndex = null;
            StateHasChanged();
            return;
        }

        var draggedCol = _columns[_draggedColumnIndex.Value];
        _columns.RemoveAt(_draggedColumnIndex.Value);
        
        // Adjust index if dragging from left to right
        var insertIndex = _draggedColumnIndex.Value < columnIndex ? columnIndex - 1 : columnIndex;
        _columns.Insert(insertIndex, draggedCol);

        _draggedColumnIndex = null;
        _dropTargetIndex = null;
        StateHasChanged();
    }

    private void OnColumnDragEnd()
    {
        _draggedColumnIndex = null;
        _dropTargetIndex = null;
        StateHasChanged();
    }

    private void OnSearchInput(ChangeEventArgs e)
    {
        _searchText = e.Value?.ToString();
    }

    private async Task OnSearchChange(ChangeEventArgs e)
    {
        _searchText = e.Value?.ToString();
        await GoToPage(1);
    }

    private async Task OnSortClick(string columnKey)
    {
        if (_sortColumnKey == columnKey)
        {
            _sortDirection = _sortDirection switch
            {
                SgDataGridSortDirection.None => SgDataGridSortDirection.Ascending,
                SgDataGridSortDirection.Ascending => SgDataGridSortDirection.Descending,
                SgDataGridSortDirection.Descending => SgDataGridSortDirection.None,
                _ => SgDataGridSortDirection.None
            };
            if (_sortDirection == SgDataGridSortDirection.None)
                _sortColumnKey = null;
        }
        else
        {
            _sortColumnKey = columnKey;
            _sortDirection = SgDataGridSortDirection.Ascending;
        }
        
        await GoToPage(1); // Reset to first page when sort changes
    }

    private async Task OnPageSizeChange(ChangeEventArgs e)
    {
        if (int.TryParse(e.Value?.ToString(), out var newSize))
        {
            await HandlePageSizeChange(newSize);
        }
    }

    private async Task HandlePageSizeChange(int newSize)
    {
        PageSize = newSize;
        if (PageSizeChanged.HasDelegate)
            await PageSizeChanged.InvokeAsync(PageSize);
            
        await GoToPage(1); // Reset to first page
    }

    private async Task GoToFirstPage()
    {
        await GoToPage(1);
    }

    private async Task GoToPreviousPage()
    {
        await GoToPage(CurrentPage - 1);
    }

    private async Task GoToNextPage()
    {
        await GoToPage(CurrentPage + 1);
    }

    private async Task GoToLastPage()
    {
        await GoToPage(TotalPages);
    }

    internal bool IsSelected(TItem item) => _selectedItems.Contains(item);

    internal async Task ToggleSelection(TItem item)
    {
        if (!AllowSelection) return;
        if (AllowMultiSelect)
        {
            if (_selectedItems.Contains(item))
                _selectedItems.Remove(item);
            else
                _selectedItems.Add(item);
        }
        else
        {
            _selectedItems.Clear();
            _selectedItems.Add(item);
        }
        SelectedItems = _selectedItems.ToList();
        await SelectedItemsChanged.InvokeAsync(SelectedItems);
    }

    internal async Task ToggleSelectAll()
    {
        if (!AllowSelection || !AllowMultiSelect) return;
        _selectAll = !_selectAll;
        if (_selectAll)
        {
            foreach (var item in PagedItems)
                _selectedItems.Add(item);
        }
        else
        {
            foreach (var item in PagedItems)
                _selectedItems.Remove(item);
        }
        SelectedItems = _selectedItems.ToList();
        await SelectedItemsChanged.InvokeAsync(SelectedItems);
    }

    internal async Task OnRowClick(TItem item)
    {
        if (RowClicked.HasDelegate)
            await RowClicked.InvokeAsync(item);
    }

    internal async Task OnRowDoubleClick(TItem item)
    {
        if (RowDoubleClicked.HasDelegate)
            await RowDoubleClicked.InvokeAsync(item);
    }

    private async Task ExportToCsv()
    {
        _showExportMenu = false;
        var csv = new StringBuilder();
        var cols = Columns.ToList();

        csv.AppendLine(string.Join(",", cols.Select(c => EscapeCsv(c.Title))));
        foreach (var item in FilteredAndSortedItems)
        {
            var values = cols.Select(c => EscapeCsv(c.GetDisplay(item)));
            csv.AppendLine(string.Join(",", values));
        }

        var fileName = $"{Title ?? "export"}_{DateTime.Now:yyyyMMdd_HHmmss}.csv";
        var content = csv.ToString();

        var bom = new byte[] { 0xEF, 0xBB, 0xBF };
        var bytes = Encoding.UTF8.GetBytes(content);
        var finalBytes = new byte[bom.Length + bytes.Length];
        Buffer.BlockCopy(bom, 0, finalBytes, 0, bom.Length);
        Buffer.BlockCopy(bytes, 0, finalBytes, bom.Length, bytes.Length);

        var base64 = Convert.ToBase64String(finalBytes);

        _jsModule ??= await JS.InvokeAsync<IJSObjectReference>(
            "import", "./_content/SuperUI/Components/Data/Table/SgTable.razor.js");
        await _jsModule.InvokeVoidAsync("downloadFile", base64, fileName, "text/csv;charset=utf-8;");
    }

    private async Task ExportToExcel()
    {
        _showExportMenu = false;
        var sb = new StringBuilder();
        var cols = Columns.ToList();

        sb.AppendLine("<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>");
        sb.AppendLine("<head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'></head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<table border='1'>");
        sb.AppendLine("  <thead>");
        sb.AppendLine("    <tr style='background-color: #f2f2f2;'>");
        foreach (var col in cols)
            sb.AppendLine($"      <th>{System.Net.WebUtility.HtmlEncode(col.Title)}</th>");
        sb.AppendLine("    </tr>");
        sb.AppendLine("  </thead>");
        sb.AppendLine("  <tbody>");
        foreach (var item in FilteredAndSortedItems)
        {
            sb.AppendLine("    <tr>");
            foreach (var col in cols)
            {
                var val = col.GetDisplay(item);
                sb.AppendLine($"      <td>{System.Net.WebUtility.HtmlEncode(val)}</td>");
            }
            sb.AppendLine("    </tr>");
        }
        sb.AppendLine("  </tbody>");
        sb.AppendLine("</table>");
        sb.AppendLine("</body></html>");

        var fileName = $"{Title ?? "export"}_{DateTime.Now:yyyyMMdd_HHmmss}.xls";
        var content = sb.ToString();

        var bom = new byte[] { 0xEF, 0xBB, 0xBF };
        var bytes = Encoding.UTF8.GetBytes(content);
        var finalBytes = new byte[bom.Length + bytes.Length];
        Buffer.BlockCopy(bom, 0, finalBytes, 0, bom.Length);
        Buffer.BlockCopy(bytes, 0, finalBytes, bom.Length, bytes.Length);

        var base64 = Convert.ToBase64String(finalBytes);

        _jsModule ??= await JS.InvokeAsync<IJSObjectReference>(
            "import", "./_content/SuperUI/Components/Data/Table/SgTable.razor.js");
        await _jsModule.InvokeVoidAsync("downloadFile", base64, fileName, "application/vnd.ms-excel");
    }

    private void ToggleExportMenu()
    {
        _showExportMenu = !_showExportMenu;
    }

    private async Task HandleExportFocusOut()
    {
        try
        {
            await Task.Delay(200, GetLifetimeToken());
        }
        catch (TaskCanceledException) { return; }
        if (_disposed) return;
        _showExportMenu = false;
        await InvokeAsync(StateHasChanged);
    }

    public async ValueTask DisposeAsync()
    {
        if (_disposed) return;
        _disposed = true;


        _lifetimeCts?.Cancel();
        _lifetimeCts?.Dispose();
        if (_jsModule is not null)
        {
            try
            {
                await _jsModule.InvokeVoidAsync("resetResizeState");
            }
            catch (JSDisconnectedException) { }
            catch (TaskCanceledException) { }
            catch (ObjectDisposedException) { }

            try
            {
                await _jsModule.DisposeAsync();
            }
            catch (JSDisconnectedException) { }
            catch (TaskCanceledException) { }
            catch (ObjectDisposedException) { }
        }
        _jsModule = null;

        await base.DisposeAsync();
    }

    private CancellationToken GetLifetimeToken()
    {
        _lifetimeCts ??= new CancellationTokenSource();
        return _lifetimeCts.Token;
    }

    private static string EscapeCsv(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        if (value.Contains(',') || value.Contains('"') || value.Contains('\n'))
        {
            return $"\"{value.Replace("\"", "\"\"")}\"";
        }
        return value;
    }
}



