using Microsoft.JSInterop;
using SuperUI.Themes;

namespace SuperUI.Services;

/// <summary>
/// Extended theme management service for SuperUI.
/// Supports multiple themes and light/dark modes.
///
/// 2.0-rc3 (PR #5, B1) — debounce + batch:
/// - All state-mutating calls go through a 150 ms debounce; the trailing
///   call persists state in one round-trip via
///   <c>SuperUI.applyThemeState({...})</c> instead of 5 separate
///   <c>localStorage.setItem</c> + 6 <c>eval</c> calls per change.
/// - <see cref="InitializeAsync"/> is idempotent: re-entering it is a no-op
///   while the module is already loaded, and is a no-op after disposal.
/// - <see cref="DisposeAsync"/> captures the <see cref="ThemeChanged"/>
///   delegate locally before nulling it, so any in-flight invocation
///   finishes against a stable handler list (prevents the "collection
///   modified during iteration" race that the previous null-out caused
///   when subscribers fired during teardown).
///
/// 2.0-rc3 (PR #5b, B3) — link swap:
/// - C# no longer generates the per-theme CSS at runtime. One .css per
///   theme lives at <c>_content/SuperUI/themes/css/{id}.css</c>, built
///   once by <c>tools/ThemeCssExporter</c> and served as a static web
///   asset with immutable cache headers. The runtime DTO ships a path
///   instead of a 15-33 KB CSS string; the JS side mutates a single
///   <c>&lt;link rel="stylesheet"&gt;</c> element in place, so the browser
///   cache does the work after the first load.
///
/// 2.0-rc3 (PR #5c) — root-cause fix for the silent theme-swap failure:
/// The C# side imports the JS module via <c>import("./_content/SuperUI/superui-theme.js")</c>
/// but the JS file is an IIFE that only assigns its API to
/// <c>window.SuperUI</c> and never <c>export</c>s anything. Calling
/// <c>_module.InvokeVoidAsync("applyThemeState", …)</c> therefore
/// throws <c>TypeError: moduleExports.applyThemeState is not a function</c>,
/// which is silently swallowed by the JSException handler below. The
/// C# state still updates (so the button label changes) but no DOM/CSS
/// effect is ever applied. The fix: invoke the global functions
/// (<c>SuperUI.applyThemeState</c>, <c>SuperUI.getSavedState</c>,
/// <c>SuperUI.initAutoMode</c>) directly via <see cref="IJSRuntime"/>,
/// bypassing the module reference. The import is still performed as a
/// reachability probe (and so the runtime knows JS is up).
/// </summary>
public sealed class SgThemeService : IAsyncDisposable
{
    private const string StorageKeyThemeId   = "superui-theme-id";
    private const string StorageKeyDarkMode  = "superui-dark-mode";
    private const string StorageKeyFontSize  = "superui-font-size";
    private const string StorageKeyFontFamily = "superui-font-family";
    private const string StorageKeyDensity   = "superui-density";

    private const int DebounceMilliseconds = 150;

    /// <summary>
    /// Static web asset base for pre-built theme stylesheets (PR #5b B3).
    /// One file per theme: <c>{base}/{id}.css</c>, generated by
    /// <c>tools/ThemeCssExporter</c> and served by the Razor SDK as a
    /// <c>_content/SuperUI/</c> asset with immutable cache headers.
    /// </summary>
    private const string ThemeCssBasePath = "_content/SuperUI/themes/css";

    private readonly IJSRuntime  _js;
    private readonly ThemeRegistry _registry;
    private IJSObjectReference?  _module;
    private bool _isDisposed;
    private bool _isInitialized;

    // Debounce machinery: each new mutation cancels the prior pending flush
    // and schedules a new one. The pending CTS is replaced atomically.
    private CancellationTokenSource? _debounceCts;
    private readonly object _debounceLock = new();

    /// <summary>Current active theme definition.</summary>
    public IThemeDefinition CurrentTheme { get; private set; }

    /// <summary>Current mode: "light" | "dark" | "auto".</summary>
    public string CurrentMode { get; private set; } = "light";

    public string FontSize { get; private set; } = "md";
    public string FontFamily { get; private set; } = "sans";
    public string Density { get; private set; } = "relaxed";

    /// <summary>true if currently in dark mode.</summary>
    public bool IsDark => CurrentMode == "dark" || (CurrentMode == "auto" && _systemPrefersDark);

    private bool _systemPrefersDark;

    /// <summary>Event raised when theme or mode changes.</summary>
    public event Action<IThemeDefinition, string>? ThemeChanged;

    public SgThemeService(IJSRuntime js, ThemeRegistry registry)
    {
        _js = js;
        _registry = registry;
        CurrentTheme = registry.GetDefault();
    }

    /// <summary>Initializes theme service and loads saved preferences.</summary>
    /// <remarks>Idempotent: subsequent calls are no-ops until disposal.</remarks>
    public async Task InitializeAsync()
    {
        if (_isDisposed) return;
        if (_isInitialized) return;
        if (_module is not null) return;

        try
        {
            // We import the module just to confirm it's reachable; the actual
            // API surface we use lives on `window.SuperUI` (set up by the
            // superui-theme.js IIFE). Calling `_module.InvokeVoidAsync` would
            // fail because the JS file has no `export` statements — the
            // TypeError would be silently caught at ApplyThemeAsync:266 and
            // every theme change would become a no-op.
            _module = await _js.InvokeAsync<IJSObjectReference>("import", "./_content/SuperUI/superui-theme.js");

            // Load saved settings in a single JS round-trip (batched).
            var saved = await _js.InvokeAsync<ThemeStateDto>("SuperUI.getSavedState");

            // Determine system preference
            _systemPrefersDark = await _js.InvokeAsync<bool>("eval", "window.matchMedia('(prefers-color-scheme: dark)').matches");

            if (saved is not null)
            {
                if (!string.IsNullOrEmpty(saved.ThemeId) && _registry.TryGet(saved.ThemeId, out var theme))
                {
                    CurrentTheme = theme!;
                }
                CurrentMode   = saved.Mode      ?? "light";
                FontSize      = saved.FontSize  ?? "md";
                FontFamily    = saved.FontFamily ?? "sans";
                Density       = saved.Density   ?? "relaxed";
            }

            // Tell the JS module which "auto" mode should subscribe to system
            // changes (B2). Idempotent on the JS side.
            await _js.InvokeVoidAsync("SuperUI.initAutoMode", CurrentMode == "auto");

            _isInitialized = true;
            await ApplyThemeAsync();
        }
        catch (JSException) { }
        catch (JSDisconnectedException) { }
        catch (TaskCanceledException) { }
        catch (ObjectDisposedException) { }
        catch (InvalidOperationException) { /* prerender */ }
    }

    public Task SetFontSizeAsync(string size)
    {
        FontSize = size;
        return ScheduleApplyAsync();
    }

    public Task SetFontFamilyAsync(string family)
    {
        FontFamily = family;
        return ScheduleApplyAsync();
    }

    public Task SetDensityAsync(string density)
    {
        Density = density;
        return ScheduleApplyAsync();
    }

    /// <summary>Sets theme by ID.</summary>
    public Task SetThemeAsync(string themeId)
    {
        if (_isDisposed) return Task.CompletedTask;
        if (!_registry.TryGet(themeId, out var theme)) return Task.CompletedTask;

        CurrentTheme = theme!;
        return ScheduleApplyAsync();
    }

    /// <summary>Sets theme by object.</summary>
    public Task SetThemeAsync(IThemeDefinition theme)
    {
        if (_isDisposed) return Task.CompletedTask;
        CurrentTheme = theme;
        return ScheduleApplyAsync();
    }

    /// <summary>Sets mode: "light" | "dark" | "auto".</summary>
    public Task SetModeAsync(string mode)
    {
        if (_isDisposed) return Task.CompletedTask;
        CurrentMode = mode;
        // Re-arm the matchMedia subscription when the mode changes.
        if (_module is not null)
        {
            // Fire-and-forget: the matchMedia listener re-attaches on the
            // JS side, and any error is non-fatal (next apply will still
            // set data-theme from the DTO).
            _ = SafeVoidAsync(_js.InvokeVoidAsync("SuperUI.initAutoMode", mode == "auto"));
        }
        return ScheduleApplyAsync();
    }

    /// <summary>Toggles light ↔ dark.</summary>
    public Task ToggleModeAsync()
    {
        var newMode = IsDark ? "light" : "dark";
        return SetModeAsync(newMode);
    }

    public IReadOnlyList<IThemeDefinition> GetAvailableThemes() => _registry.GetAll();

    /// <summary>
    /// Coalesces rapid mutations into a single apply 150 ms after the last
    /// change. Cancellation is done by replacing the pending CTS; only the
    /// trailing caller actually reaches the JS interop layer.
    /// </summary>
    private Task ScheduleApplyAsync()
    {
        if (_isDisposed) return Task.CompletedTask;
        if (_module is null) return Task.CompletedTask; // not initialized; ignore

        CancellationToken token;
        lock (_debounceLock)
        {
            _debounceCts?.Cancel();
            _debounceCts?.Dispose();
            _debounceCts = new CancellationTokenSource();
            token = _debounceCts.Token;
        }

        return DebounceAsync(token);
    }

    private async Task DebounceAsync(CancellationToken token)
    {
        try
        {
            await Task.Delay(DebounceMilliseconds, token);
        }
        catch (OperationCanceledException)
        {
            return; // superseded by a newer ScheduleApplyAsync call
        }
        catch (ObjectDisposedException)
        {
            return; // service disposed during the wait
        }

        if (_isDisposed || token.IsCancellationRequested) return;

        await ApplyThemeAsync();
    }

    private async Task ApplyThemeAsync()
    {
        if (_isDisposed) return;
        // _module is set during InitializeAsync; if it's null, the JS
        // runtime never came up (prerender, JS disabled, import failed),
        // so we have nothing to call into. We still update the C# state
        // so a later retry via SetXxxAsync works once the JS bridge is
        // available again.
        if (_module is null) return;

        var effectiveDark = IsDark;
        var dataTheme = effectiveDark ? "dark" : "light";

        var fontFamilyValue = FontFamily == "mono" ? "mono" : "sans";
        var densityValue = Density == "compact" ? "compact" : "relaxed";
        var fontSizeValue = FontSize switch { "sm" => "sm", "lg" => "lg", _ => "md" };

        // PR #5b B3: ship a path, not a CSS string. The CSS itself lives in
        // a pre-built .css file under /_content/SuperUI/themes/css/{id}.css
        // and is mutated in place by superui-theme.js. Browser cache +
        // gzip handle repeat swaps.
        var themeHref = $"{ThemeCssBasePath}/{CurrentTheme.Id}.css";

        // Single JS round-trip: persist + apply. We go through
        // window.SuperUI (set up by superui-theme.js) instead of the
        // module reference because the JS file has no `export` statements
        // — the IIFE only assigns to window.SuperUI.
        try
        {
            await _js.InvokeVoidAsync("SuperUI.applyThemeState", new ThemeStateDto
            {
                ThemeId    = CurrentTheme.Id,
                Mode       = CurrentMode,
                FontSize   = FontSize,
                FontFamily = FontFamily,
                Density    = Density,
                ThemeHref  = themeHref,
                DataTheme  = dataTheme,
                AttrFontFamily = fontFamilyValue,
                AttrDensity    = densityValue,
                AttrFontSize   = fontSizeValue,
            });
        }
        catch (JSException) { }
        catch (JSDisconnectedException) { }
        catch (TaskCanceledException) { }
        catch (ObjectDisposedException) { }
        catch (InvalidOperationException) { /* prerender: JS not yet available */ }

        // Capture the delegate locally before invoking so that a concurrent
        // DisposeAsync that nulls the event cannot race the invocation.
        var handler = ThemeChanged;
        if (handler is not null)
        {
            try { handler(CurrentTheme, CurrentMode); }
            catch { /* подписчик упал — не наш контракт */ }
        }
    }

    private async Task SafeVoidAsync(ValueTask task)
    {
        try { await task; }
        catch (JSException) { }
        catch (JSDisconnectedException) { }
        catch (TaskCanceledException) { }
        catch (ObjectDisposedException) { }
        catch (InvalidOperationException) { }
    }

    public async ValueTask DisposeAsync()
    {
        if (_isDisposed) return;
        _isDisposed = true;

        // Cancel any pending debounce flush.
        CancellationTokenSource? cts;
        lock (_debounceLock)
        {
            cts = _debounceCts;
            _debounceCts = null;
        }
        if (cts is not null)
        {
            try { cts.Cancel(); } catch (ObjectDisposedException) { }
            cts.Dispose();
        }

        // Capture the current ThemeChanged delegate locally so subscribers
        // still see a consistent list during the teardown, then null the
        // event so no new subscribers can attach after Dispose.
        var existingHandler = ThemeChanged;
        ThemeChanged = null;

        var module = _module;
        _module = null;
        _isInitialized = false;
        if (module is not null)
        {
            try { await module.DisposeAsync(); }
            catch (JSDisconnectedException) { }
            catch (TaskCanceledException) { }
            catch (ObjectDisposedException) { }
        }

        GC.SuppressFinalize(this);
    }

    // DTO mirrored on the JS side; field names are camelCased by the
    // interop layer so superui-theme.js can read them as state.themeId etc.
    private sealed class ThemeStateDto
    {
        public string? ThemeId    { get; set; }
        public string? Mode       { get; set; }
        public string? FontSize   { get; set; }
        public string? FontFamily { get; set; }
        public string? Density    { get; set; }
        public string  ThemeHref  { get; set; } = ""; // PR #5b B3
        public string? DataTheme  { get; set; }
        public string? AttrFontFamily { get; set; }
        public string? AttrDensity    { get; set; }
        public string? AttrFontSize   { get; set; }
    }
}
