using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.Extensions.Logging;
using Microsoft.JSInterop;
using SuperUI.Localization;
using SuperUI.Base.Utilities;
using System.Collections;
using SuperUI.Enums;
using SortDirection = SuperUI.Enums.SgDataGridSortDirection;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Encodings.Web;

namespace SuperUI.Components;

public partial class SgDataGrid<TItem> : ComponentBase, IAsyncDisposable where TItem : notnull
{
    private readonly HashSet<string> _hiddenColumns = new(StringComparer.Ordinal);
    private readonly HashSet<string> _pinnedColumns = new(StringComparer.Ordinal);
    internal readonly Dictionary<string, int> _columnWidths = new(StringComparer.Ordinal);
    internal readonly Dictionary<string, int> _columnOrder = new(StringComparer.Ordinal);
    internal readonly Dictionary<string, SgDataGridColumn<TItem>> _columnLookup = new(StringComparer.Ordinal);
    private int _columnsVersion = 0;

    // Working copies for column chooser
    private HashSet<string> _chooserHiddenColumns = new(StringComparer.Ordinal);
    private HashSet<string> _chooserPinnedColumns = new(StringComparer.Ordinal);

    private bool _showChooser;
    internal bool _showExportMenu;

    private TItem? _activeRow = default;
    private TItem? _lastSelectedItem = default;
    private int _selectionVersion;
    private bool _selectionChangedPending;

    // Bulk edit state
    private bool _bulkEditPickerOpen;
    private bool _bulkEditModalOpen;
    private readonly HashSet<string> _bulkEditSelectedColumns = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string?> _bulkEditValues = new(StringComparer.Ordinal);

    // Edit form validation
    private readonly Dictionary<string, string> _editFormErrors = new(StringComparer.Ordinal);
    private bool _editModalVisible;
    private string? _editModalTitle;
    private List<SgDataGridColumn<TItem>>? _editFormColumns;
    private readonly Dictionary<string, string?> _editFormValues = new(StringComparer.Ordinal);
    private TItem? _editingCellItem;
    private string? _editingCellColumnKey;
    private string? _editingCellValue;
    private bool _isEditMode;
    private TItem? _editModalItem;

    // Row highlighting
    internal readonly List<RowHighlightRule> _rowHighlightRules = new();
    private bool _rowHighlighterModalOpen;

    // Delete
    private readonly Stack<DeletedRowEntry> _deletedRows = new();
    private readonly HashSet<TItem> _expandedRows = new();

    private TItem? _anchorRow;

    // Pinned offsets cache
    private int _pinnedLeftOffsetsCacheVersion = -1;
    private Dictionary<string, int>? _pinnedLeftOffsetsCache;

    internal bool HasUndoDelete => _deletedRows.Count > 0;
    internal bool CanCreateInlineItem => CreateItemFactory is not null || typeof(TItem).GetConstructor(Type.EmptyTypes) is not null;
    public HashSet<TItem> SelectedItems { get; } = new();

    internal bool AllFilteredSelected
    {
        get
        {
            var selectedCount = SelectedItems.Count;
            var currentKey = (_itemsVersion, _filterVersion, _selectionVersion, selectedCount);
            if (_allFilteredSelectedCacheKey == currentKey)
            {
                return _allFilteredSelectedCacheValue;
            }

            var rows = GetFilteredRows();
            _allFilteredSelectedCacheValue = rows.Count > 0 && rows.All(SelectedItems.Contains);
            _allFilteredSelectedCacheKey = currentKey;
            return _allFilteredSelectedCacheValue;
        }
    }

    internal IReadOnlyList<SgDataGridColumn<TItem>> VisibleColumns
    {
        get
        {
            EnsureAutoGeneratedColumns();
            if (_visibleColumnsCacheVersion == _columnsVersion && _visibleColumnsCache is not null)
                return _visibleColumnsCache;

            _visibleColumnsCache = GetOrderedColumns()
                .Where(c => !_hiddenColumns.Contains(c.Key))
                .ToList();
            _visibleColumnsCacheVersion = _columnsVersion;
            return _visibleColumnsCache;
        }
    }

    private string _editModalWidth => $"{EditModalWidth}px";

    // ── Column management ───────────────────────────────────────────────────────

    internal void RegisterColumn(SgDataGridColumn<TItem> column)
    {
        if (_columns.Contains(column))
            return;

        if (_columns.Any(c => !c.IsSynthetic))
        {
            _columns.RemoveAll(c => c.IsSynthetic);
        }

        _columns.Add(column);
        RebuildColumnLookup();
        if (!_columnOrder.ContainsKey(column.Key))
            _columnOrder[column.Key] = _columnOrder.Count;
        if (column.Hidden)
            _hiddenColumns.Add(column.Key);
        _visibleColumnsCache = null;
        _columnsVersion++;
        _numericColumnCache.Clear();

        DetectNumericColumn(column);
    }

    internal void UnregisterColumn(SgDataGridColumn<TItem> column)
    {
        _columns.Remove(column);
        RebuildColumnLookup();
        _columnsVersion++;
    }

    internal IReadOnlyList<SgDataGridColumn<TItem>> GetOrderedColumns()
    {
        if (_orderedColumnsCacheColumnsVersion == _columnsVersion && _orderedColumnsCache is not null)
            return _orderedColumnsCache;

        _orderedColumnsCache = _columns
            .Select((column, index) => (column, index))
            .OrderBy(x => IsColumnPinned(x.column.Key) ? 0 : 1)
            .ThenBy(x => _columnOrder.TryGetValue(x.column.Key, out var order) ? order : int.MaxValue)
            .ThenBy(x => x.index)
            .Select(x => x.column)
            .ToList();

        _orderedColumnsCacheColumnsVersion = _columnsVersion;
        return _orderedColumnsCache;
    }

    private SgDataGridColumn<TItem>? GetColumnByKey(string key)
    {
        if (_columnLookup.Count != _columns.Count)
            RebuildColumnLookup();

        return _columnLookup.TryGetValue(key, out var col) ? col : null;
    }

    private void RebuildColumnLookup()
    {
        _columnLookup.Clear();
        for (var i = 0; i < _columns.Count; i++)
        {
            var column = _columns[i];
            _columnLookup[column.Key] = column;
        }
    }

    internal bool IsColumnHidden(string key) => _showChooser ? _chooserHiddenColumns.Contains(key) : _hiddenColumns.Contains(key);

    internal bool IsColumnPinned(string key)
    {
        var pinnedSet = _showChooser ? _chooserPinnedColumns : _pinnedColumns;
        var result = pinnedSet.Contains(key) || (GetColumnByKey(key)?.Pinned == true);
        return result;
    }

    private async Task ToggleColumnHiddenAsync(string key, bool hidden)
    {
        if (hidden)
            _chooserHiddenColumns.Add(key);
        else
            _chooserHiddenColumns.Remove(key);
        await InvokeAsync(StateHasChanged);
    }

    private async Task ToggleColumnPinnedAsync(string key, bool pin)
    {
        if (pin)
            _chooserPinnedColumns.Add(key);
        else
            _chooserPinnedColumns.Remove(key);
        await InvokeAsync(StateHasChanged);
    }

    private string GetColumnWidthStyle(SgDataGridColumn<TItem> col)
    {
        if (_columnWidths.TryGetValue(col.Key, out var width) && width > 0)
            return $"width:{width}px;min-width:{width}px;";

        if (!string.IsNullOrWhiteSpace(col.Width))
        {
            var w = col.Width;
            if (!w.EndsWith("px", StringComparison.OrdinalIgnoreCase) && 
                !w.EndsWith("%", StringComparison.OrdinalIgnoreCase) &&
                !w.EndsWith("em", StringComparison.OrdinalIgnoreCase) &&
                !w.EndsWith("rem", StringComparison.OrdinalIgnoreCase))
            {
                if (int.TryParse(w, out _))
                    w = w + "px";
            }
            return $"width:{w};min-width:{w};";
        }

        return string.Empty;
    }

    private string GetColumnPinStyle(SgDataGridColumn<TItem> col)
    {
        if (!IsColumnPinned(col.Key))
            return string.Empty;

        EnsurePinnedLeftOffsets();
        if (_pinnedLeftOffsetsCache is not null && _pinnedLeftOffsetsCache.TryGetValue(col.Key, out var left))
        {
            return $"position:sticky;left:{left}px;z-index:3;";
        }

        return string.Empty;
    }

    private string GetColumnPinStyleForHeader(SgDataGridColumn<TItem> col)
    {
        if (!IsColumnPinned(col.Key))
            return string.Empty;

        EnsurePinnedLeftOffsets();
        if (_pinnedLeftOffsetsCache is not null && _pinnedLeftOffsetsCache.TryGetValue(col.Key, out var left))
        {
            return $"position:sticky;top:0;left:{left}px;z-index:4;background:var(--sg-header-bg);";
        }

        return string.Empty;
    }

    private string GetColumnPinStyleForQuickFilter(SgDataGridColumn<TItem> col)
    {
        if (!IsColumnPinned(col.Key))
            return string.Empty;

        EnsurePinnedLeftOffsets();
        if (_pinnedLeftOffsetsCache is not null && _pinnedLeftOffsetsCache.TryGetValue(col.Key, out var left))
        {
            return $"position:sticky;top:30px;left:{left}px;z-index:6;background:var(--sg-header-bg);";
        }

        return string.Empty;
    }

    private string GetColumnTdClass(SgDataGridColumn<TItem> col, bool isNumeric = false)
    {
        var css = "sg-td";
        if (IsColumnPinned(col.Key))
            css += " sg-pinned";
        if (col.Editable && col.OnValueChanged is not null)
            css += " sg-editable";

        if (isNumeric)
            css += " sg-td-numeric";

        var hAlign = col.HAlign;
        if (hAlign == SgColumnAlign.Default && isNumeric)
            hAlign = SgColumnAlign.Right;

        css += hAlign switch
        {
            SgColumnAlign.Left   => " sg-align-left",
            SgColumnAlign.Center => " sg-align-center",
            SgColumnAlign.Right  => " sg-align-right",
            _               => string.Empty
        };

        var valign = (int)col.VAlign;
        css += valign switch
        {
            0 => string.Empty,
            1 => " sg-valign-top",
            2 => " sg-valign-middle",
            3 => " sg-valign-bottom",
            _ => string.Empty
        };

        return css;
    }

    private int EstimateWidth(SgDataGridColumn<TItem> col)
    {
        if (_columnWidths.TryGetValue(col.Key, out var width))
            return width;

        if (!string.IsNullOrWhiteSpace(col.Width))
        {
            var s = col.Width.AsSpan();
            var i = 0;
            while (i < s.Length && !char.IsAsciiDigit(s[i])) i++;
            var start = i;
            while (i < s.Length && char.IsAsciiDigit(s[i])) i++;
            if (i > start && int.TryParse(s[start..i], out var parsed))
                return parsed;
        }

        return 140;
    }

    // ── Technical column helpers ────────────────────────────────────────────────

    private int GetTechnicalColumnLeft(string columnType)
    {
        var left = 0;
        
        if (columnType == "expand")
        {
            if (ShowRowNumbers) left += 36;
            return left;
        }
        
        if (columnType == "tree")
        {
            if (ShowRowNumbers) left += 36;
            if ((DetailTemplate is not null || AutoDetail) && DetailPlacement == DetailPlacement.Inline) left += 32;
            return left;
        }
        
        if (columnType == "check")
        {
            if (ShowRowNumbers) left += 36;
            if ((DetailTemplate is not null || AutoDetail) && DetailPlacement == DetailPlacement.Inline) left += 32;
            if (IsTree) left += 32;
            return left;
        }
        
        return 0;
    }

    private string GetTechnicalColumnPinStyle(string columnType)
    {
        var left = GetTechnicalColumnLeft(columnType);
        return $"position:sticky;left:{left}px;z-index:3;";
    }

    private string GetLastTechnicalColumnType()
    {
        if (SelectionEnabled) return "check";
        if (IsTree) return "tree";
        if ((DetailTemplate is not null || AutoDetail) && DetailPlacement == DetailPlacement.Inline) return "expand";
        if (ShowRowNumbers) return "rownum";
        return "";
    }

    private string GetTechnicalColumnClass(string baseClass, string columnType)
    {
        var lastType = GetLastTechnicalColumnType();
        var isLast = columnType == lastType;
        return isLast ? $"{baseClass} sg-last-pinned-tech" : baseClass;
    }

    private void EnsurePinnedLeftOffsets()
    {
        if (_pinnedLeftOffsetsCacheVersion == _columnsVersion && _pinnedLeftOffsetsCache is not null)
            return;

        _pinnedLeftOffsetsCache ??= new Dictionary<string, int>(StringComparer.Ordinal);
        _pinnedLeftOffsetsCache.Clear();

        var left = 0;

        if (ShowRowNumbers) left += 36;
        if ((DetailTemplate is not null || AutoDetail) && DetailPlacement == DetailPlacement.Inline)
            left += 32;
        if (IsTree) left += 32;
        if (SelectionEnabled) left += 28;

        var visibleColumns = VisibleColumns;
        
        for (var i = 0; i < visibleColumns.Count; i++)
        {
            var column = visibleColumns[i];
            
            if (!IsColumnPinned(column.Key))
                continue;

            var width = EstimateWidth(column);
            _pinnedLeftOffsetsCache[column.Key] = left;
            left += width;
        }

        _pinnedLeftOffsetsCacheVersion = _columnsVersion;
    }

    // ── Chooser ─────────────────────────────────────────────────────────────────

    private async Task ToggleChooserAsync()
    {
        if (!_showChooser)
        {
            _chooserHiddenColumns = new HashSet<string>(_hiddenColumns, StringComparer.Ordinal);
            _chooserPinnedColumns = new HashSet<string>(_pinnedColumns, StringComparer.Ordinal);
        }
        _showChooser = !_showChooser;
        _showExportMenu = false;
        _showSortBuilder = false;
        _showGroupBuilder = false;
        _showSavedViewsPanel = false;
        await InvokeAsync(StateHasChanged);
    }

    private async Task HandleChooserFocusOutAsync(FocusEventArgs _)
    {
        await Task.CompletedTask;
    }

    private async Task ApplyChooserChangesAsync()
    {
        try
        {
            _showChooser = false;
            
            _hiddenColumns.Clear();
            foreach (var key in _chooserHiddenColumns)
                _hiddenColumns.Add(key);

            _pinnedColumns.Clear();
            foreach (var key in _chooserPinnedColumns)
                _pinnedColumns.Add(key);

            _columnsVersion++;
            _pinnedLeftOffsetsCache = null;
            _pinnedLeftOffsetsCacheVersion = -1;
            _visibleColumnsCache = null;
            _visibleColumnsCacheVersion = -1;
            _columnSpanCacheVersion = -1;
            _orderedColumnsCache = null;
            _orderedColumnsCacheColumnsVersion = -1;
            InvalidateComputedRowsCache();
            
            EnsurePinnedLeftOffsets();
            
            await InvokeAsync(StateHasChanged);
            await SaveStateAsync();
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "[DataGrid] ApplyChooserChangesAsync failed");
        }
    }

    private async Task ApplyChooserChangesWithoutClosingAsync()
    {
        try
        {
            _hiddenColumns.Clear();
            foreach (var key in _chooserHiddenColumns)
                _hiddenColumns.Add(key);

            _pinnedColumns.Clear();
            foreach (var key in _chooserPinnedColumns)
                _pinnedColumns.Add(key);

            _columnsVersion++;
            _pinnedLeftOffsetsCache = null;
            _pinnedLeftOffsetsCacheVersion = -1;
            _visibleColumnsCache = null;
            _visibleColumnsCacheVersion = -1;
            _columnSpanCacheVersion = -1;
            _orderedColumnsCache = null;
            _orderedColumnsCacheColumnsVersion = -1;
            InvalidateComputedRowsCache();
            
            EnsurePinnedLeftOffsets();
            
            await InvokeAsync(StateHasChanged);
            await SaveStateAsync();
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "[DataGrid] ApplyChooserChangesWithoutClosingAsync failed");
        }
    }

    private async Task CancelChooserChangesAsync()
    {
        _chooserHiddenColumns = new HashSet<string>(_hiddenColumns, StringComparer.Ordinal);
        _chooserPinnedColumns = new HashSet<string>(_pinnedColumns, StringComparer.Ordinal);
        _showChooser = false;
        await InvokeAsync(StateHasChanged);
    }

    private Task ToggleExportMenuAsync()
    {
        _showExportMenu = !_showExportMenu;
        _showChooser = false;
        _showSortBuilder = false;
        _showGroupBuilder = false;
        _showSavedViewsPanel = false;
        return Task.CompletedTask;
    }

    private async Task HandleExportFocusOutAsync(FocusEventArgs _)
    {
        await Task.Delay(150);
        _showExportMenu = false;
    }

    // ── Selection ───────────────────────────────────────────────────────────────

    public async Task SelectAllAsync()
    {
        var rows = GetFilteredRows();
        var changed = false;
        foreach (var row in rows)
        {
            if (RowDisabled?.Invoke(row) == true) continue;
            if (SelectedItems.Add(row)) changed = true;
        }
        if (changed)
        {
            _selectionVersion++;
            if (SelectedItemsChanged.HasDelegate)
                await SelectedItemsChanged.InvokeAsync(SelectedItems);
            await InvokeAsync(StateHasChanged);
        }
    }

    public async Task DeselectAllAsync()
    {
        if (SelectedItems.Count == 0) return;
        SelectedItems.Clear();
        _selectionVersion++;
        if (SelectedItemsChanged.HasDelegate)
            await SelectedItemsChanged.InvokeAsync(SelectedItems);
        await InvokeAsync(StateHasChanged);
    }

    public async Task SelectItemsAsync(IEnumerable<TItem> items, bool clearExisting = false)
    {
        if (clearExisting) SelectedItems.Clear();
        var changed = false;
        foreach (var item in items)
        {
            if (RowDisabled?.Invoke(item) == true) continue;
            if (SelectedItems.Add(item)) changed = true;
        }
        if (changed)
        {
            _selectionVersion++;
            if (SelectedItemsChanged.HasDelegate)
                await SelectedItemsChanged.InvokeAsync(SelectedItems);
            await InvokeAsync(StateHasChanged);
        }
    }

    private async Task ToggleRowAsync(TItem item, bool selected)
    {
        if (RowDisabled?.Invoke(item) == true) return;
        if (AllowSingleSelect && !AllowMultiSelect)
        {
            SelectedItems.Clear();
            if (selected)
            {
                SelectedItems.Add(item);
                _lastSelectedItem = item;
            }
            else
            {
                _lastSelectedItem = default;
            }
        }
        else
        {
            if (selected)
            {
                SelectedItems.Add(item);
                _lastSelectedItem = item;
            }
            else
            {
                SelectedItems.Remove(item);
                if (ReferenceEquals(_lastSelectedItem, item))
                    _lastSelectedItem = default;
            }
        }

        _selectionVersion++;
        _selectionChangedPending = true;
        InvalidateComputedRowsCache();
        await FlushSelectedItemsChangedAsync();
        if (AllowSingleSelect && selected)
            await OnRowClickAsync(item);
    }

    private async Task HandleRowSelectionClickAsync(MouseEventArgs args, TItem item)
    {
        if (!AllowSingleSelect && args.ShiftKey && _lastSelectedItem != null && !ReferenceEquals(_lastSelectedItem, item))
        {
            var rows = GetVisibleRows();
            var lastIdx = rows.IndexOf(_lastSelectedItem);
            var currIdx = rows.IndexOf(item);

            if (lastIdx != -1 && currIdx != -1)
            {
                var start = Math.Min(lastIdx, currIdx);
                var end = Math.Max(lastIdx, currIdx);

                var shouldSelect = SelectedItems.Contains(_lastSelectedItem);
                for (var i = start; i <= end; i++)
                {
                    if (shouldSelect)
                        SelectedItems.Add(rows[i]);
                    else
                        SelectedItems.Remove(rows[i]);
                }

                _selectionVersion++;
                _selectionChangedPending = true;
                InvalidateComputedRowsCache();
                await FlushSelectedItemsChangedAsync();
                return;
            }
        }
    }

    private async Task OnToggleAllAsync(ChangeEventArgs args)
    {
        var selected = args.Value is true;
        var rows = GetFilteredRows();

        if (selected)
        {
            SelectedItems.UnionWith(rows);
        }
        else
        {
            SelectedItems.ExceptWith(rows);
        }

        _selectionVersion++;
        _selectionChangedPending = true;
        InvalidateComputedRowsCache();
        await FlushSelectedItemsChangedAsync();
    }

    public async Task ClearSelectionAsync()
    {
        SelectedItems.Clear();
        _selectionVersion++;
        _selectionChangedPending = true;
        InvalidateComputedRowsCache();
        await FlushSelectedItemsChangedAsync();
    }

    public async Task SelectItemAsync(TItem item)
    {
        if (RowDisabled?.Invoke(item) == true) return;
        await ToggleRowAsync(item, true);
    }

    async Task SelectItemsAsync(IEnumerable<TItem> items)
    {
        var changed = false;
        foreach (var item in items)
        {
            if (RowDisabled?.Invoke(item) == true) continue;
            if (SelectedItems.Add(item)) changed = true;
        }
        if (!changed) return;
        _selectionVersion++;
        _selectionChangedPending = true;
        InvalidateComputedRowsCache();
        await FlushSelectedItemsChangedAsync();
        await InvokeAsync(StateHasChanged);
    }

    private async Task HandleRangeSelectionAsync(TItem targetRow, List<TItem> visibleRows)
    {
        _anchorRow ??= _activeRow ?? targetRow;
        var startIdx = visibleRows.IndexOf(_anchorRow);
        var endIdx = visibleRows.IndexOf(targetRow);

        if (startIdx == -1 || endIdx == -1) return;

        var min = Math.Min(startIdx, endIdx);
        var max = Math.Max(startIdx, endIdx);

        SelectedItems.Clear();
        for (var i = min; i <= max; i++)
        {
            SelectedItems.Add(visibleRows[i]);
        }

        _activeRow = targetRow;

        if (SelectedItemsChanged.HasDelegate)
            await SelectedItemsChanged.InvokeAsync(SelectedItems);

        await InvokeAsync(StateHasChanged);
    }

    private Task FlushSelectedItemsChangedAsync()
    {
        if (!_selectionChangedPending)
            return Task.CompletedTask;

        _selectionChangedPending = false;
        return SelectedItemsChanged.HasDelegate
            ? SelectedItemsChanged.InvokeAsync(SelectedItems)
            : Task.CompletedTask;
    }

    // ── Inline editing ──────────────────────────────────────────────────────────

    private bool IsEditingCell(TItem item, SgDataGridColumn<TItem> column) =>
        _editingCellColumnKey == column.Key &&
        _editingCellItem is not null &&
        EqualityComparer<TItem>.Default.Equals(_editingCellItem, item);

    private void StartCellEdit(TItem item, SgDataGridColumn<TItem> column)
    {
        _editingCellItem = item;
        _editingCellColumnKey = column.Key;
        _editingCellValue = column.GetValue(item)?.ToString() ?? string.Empty;
    }

    private void OnCellEditInput(ChangeEventArgs args)
    {
        _editingCellValue = args.Value?.ToString() ?? string.Empty;
    }

    private async Task OnCellEditKeyDownAsync(KeyboardEventArgs args, TItem item, SgDataGridColumn<TItem> column)
    {
        if (args.Key == "Enter")
        {
            await CommitCellEditAsync(item, column);
        }
        else if (args.Key == "Escape")
        {
            CancelCellEdit();
            await InvokeAsync(StateHasChanged);
        }
    }

    private async Task CommitCellEditAsync(TItem item, SgDataGridColumn<TItem> column)
    {
        column.OnValueChanged?.Invoke(item, ConvertCellEditValue(_editingCellValue, column, item));
        CancelCellEdit();
        InvalidateComputedRowsCache();
        await InvokeAsync(StateHasChanged);
    }

    private void CancelCellEdit()
    {
        _editingCellItem = default;
        _editingCellColumnKey = null;
        _editingCellValue = null;
    }

    private static object? ConvertCellEditValue(string? value, SgDataGridColumn<TItem> column, TItem item)
    {
        var targetType = column.ValueType ?? column.GetValue(item)?.GetType();
        if (targetType is null || targetType == typeof(string))
            return value;

        targetType = Nullable.GetUnderlyingType(targetType) ?? targetType;
        if (string.IsNullOrWhiteSpace(value))
            return targetType.IsValueType ? Activator.CreateInstance(targetType) : null;

        if (targetType.IsEnum)
            return Enum.Parse(targetType, value, ignoreCase: true);

        return Convert.ChangeType(value, targetType, CultureInfo.CurrentCulture);
    }

    // ── Modal editing ───────────────────────────────────────────────────────────

    private async Task StartEditModalAsync(TItem item)
    {
        _editModalItem = item;
        _isEditMode = true;
        _editModalTitle = !string.IsNullOrEmpty(EditModalEditTitle) ? EditModalEditTitle : Localizer["DataGrid_Edit"];

        var editableColumns = VisibleColumns.Where(c => c.Editable).ToList();
        if (editableColumns.Count == 0)
        {
            editableColumns = VisibleColumns
                .Where(c => !c.Key.Equals("id", StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        _editFormColumns = editableColumns;
        _editFormValues.Clear();
        _editFormErrors.Clear();

        foreach (var col in _editFormColumns)
        {
            var raw = col.GetValue(item);
            var filterType = GetColumnFilterType(col.Key);
            _editFormValues[col.Key] = filterType switch
            {
                "date" => raw is DateTime dt ? dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)
                        : raw is DateTimeOffset dto ? dto.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)
                        : raw?.ToString() ?? string.Empty,
                "datetime" => raw is DateTime dt2 ? dt2.ToString("yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
                            : raw is DateTimeOffset dto2 ? dto2.ToString("yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
                            : raw?.ToString() ?? string.Empty,
                "bool" => raw is bool b ? (b ? "true" : "false") : raw?.ToString() ?? "false",
                "enum" => raw?.ToString() ?? string.Empty,
                "number" => raw is not null ? Convert.ToDecimal(raw, CultureInfo.InvariantCulture)
                                .ToString(CultureInfo.InvariantCulture) : string.Empty,
                _ => raw?.ToString() ?? string.Empty
            };
        }

        _editModalVisible = true;
        await InvokeAsync(StateHasChanged);
    }

    private async Task StartCreateModalAsync()
    {
        _editModalItem = CreateItemFactory is not null ? CreateItemFactory() : Activator.CreateInstance<TItem>();
        _isEditMode = false;
        _editModalTitle = !string.IsNullOrEmpty(EditModalAddTitle) ? EditModalAddTitle : Localizer["DataGrid_Add"];

        var editableColumns = VisibleColumns.Where(c => c.Editable).ToList();
        if (editableColumns.Count == 0)
        {
            editableColumns = VisibleColumns
                .Where(c => !c.Key.Equals("id", StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        _editFormColumns = editableColumns;
        _editFormValues.Clear();
        _editFormErrors.Clear();

        foreach (var col in _editFormColumns)
        {
            var raw = col.GetValue(_editModalItem!);
            var filterType = GetColumnFilterType(col.Key);
            _editFormValues[col.Key] = filterType switch
            {
                "date" => raw is DateTime dt ? dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)
                        : raw is DateTimeOffset dto ? dto.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)
                        : string.Empty,
                "datetime" => raw is DateTime dt2 ? dt2.ToString("yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
                            : raw is DateTimeOffset dto2 ? dto2.ToString("yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
                            : string.Empty,
                "bool" => raw is bool b ? (b ? "true" : "false") : "false",
                "enum" => raw?.ToString() ?? string.Empty,
                "number" => raw is not null && IsNumericValue(raw)
                    ? Convert.ToDecimal(raw, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)
                    : string.Empty,
                _ => raw?.ToString() ?? string.Empty
            };
        }

        _editModalVisible = true;
        await InvokeAsync(StateHasChanged);
    }

    private Task OnEditFormInputAsync(string key, string? value)
    {
        _editFormValues[key] = value;
        return Task.CompletedTask;
    }

    private Task OnEditFormInputAsync(string key, bool value)
    {
        _editFormValues[key] = value ? "true" : "false";
        return Task.CompletedTask;
    }

    private Task OnEditFormInputAsync(string key, decimal? value)
    {
        _editFormValues[key] = value?.ToString();
        return Task.CompletedTask;
    }

    private Task OnEditFormInputAsync(string key, DateTime? value)
    {
        _editFormValues[key] = value?.ToString("yyyy-MM-dd");
        return Task.CompletedTask;
    }

    private async Task SaveEditModal(TItem item)
    {
        if (item is null)
            return;

        if (!_isEditMode)
        {
            if (Items is IList<TItem> list)
            {
                list.Insert(0, item);
                _itemsVersion++;
                _prevItemsCount = list.Count;
                InvalidateComputedRowsCache();
            }

            if (RowCreated.HasDelegate)
                await RowCreated.InvokeAsync(item);
        }
        else
        {
            InvalidateComputedRowsCache();

            if (RowDoubleClicked.HasDelegate)
                await RowDoubleClicked.InvokeAsync(item);
        }

        _editModalVisible = false;
        _editModalItem = default;
        _editFormColumns = null;
        _editFormValues.Clear();
        if (RowSaved.HasDelegate)
            await RowSaved.InvokeAsync(item);
        await InvokeAsync(StateHasChanged);
    }

    private Task CloseEditModal()
    {
        _editModalVisible = false;
        _editModalItem = default;
        _editFormColumns = null;
        _editFormValues.Clear();
        _editFormErrors.Clear();
        return Task.CompletedTask;
    }

    private RenderFragment RenderEditForm() => builder =>
    {
        if (_editModalItem is null || _editFormColumns is null)
            return;

        var seq = 0;

        builder.OpenElement(seq++, "div");
        builder.AddAttribute(seq++, "class", "sg-edit-form");

        builder.OpenElement(seq++, "div");
        builder.AddAttribute(seq++, "class", "sg-edit-form-grid");

        foreach (var col in _editFormColumns)
        {
            var colKey = col.Key;
            var filterType = GetColumnFilterType(colKey);
            var currentVal = _editFormValues.TryGetValue(colKey, out var v) ? v : string.Empty;
            var hasError = _editFormErrors.TryGetValue(colKey, out var errMsg);

            var isFullWidth = filterType == "string" && col.ValueType == typeof(string);

            builder.OpenElement(seq++, "div");
            builder.AddAttribute(seq++, "class",
                "sg-edit-form-group" + (isFullWidth ? " sg-edit-full" : ""));

            builder.OpenElement(seq++, "label");
            builder.AddAttribute(seq++, "class", "sg-edit-form-label");
            builder.AddContent(seq++, col.Title);
            builder.CloseElement();

            switch (filterType)
            {
                case "bool":
                {
                    var boolVal = currentVal is "true" or "True" or "1" or "✓";
                    builder.OpenElement(seq++, "label");
                    builder.AddAttribute(seq++, "class", "sg-checkbox-label");
                    builder.OpenElement(seq++, "input");
                    builder.AddAttribute(seq++, "type", "checkbox");
                    builder.AddAttribute(seq++, "checked", boolVal);
                    builder.AddAttribute(seq++, "onchange",
                        EventCallback.Factory.Create<ChangeEventArgs>(this, e =>
                        {
                            var val = e.Value is true ? "true" : "false";
                            _editFormValues[colKey] = val;
                            ApplyEditValueToItem(colKey, val);
                            ValidateEditField(colKey);
                            StateHasChanged();
                        }));
                    builder.CloseElement();
                    builder.AddContent(seq++, boolVal
                        ? Localizer["DataGrid_FilterTrue"]
                        : Localizer["DataGrid_FilterFalse"]);
                    builder.CloseElement();
                    break;
                }

                case "enum":
                {
                    var enumItems = GetColumnEnumItems(colKey);
                    builder.OpenElement(seq++, "select");
                    builder.AddAttribute(seq++, "class",
                        "sg-edit-form-select" + (hasError ? " sg-edit-invalid" : ""));
                    builder.AddAttribute(seq++, "value", currentVal ?? string.Empty);
                    builder.AddAttribute(seq++, "onchange",
                        EventCallback.Factory.Create<ChangeEventArgs>(this, e =>
                        {
                            var val = e.Value?.ToString();
                            _editFormValues[colKey] = val;
                            ApplyEditValueToItem(colKey, val);
                            ValidateEditField(colKey);
                            StateHasChanged();
                        }));
                    builder.OpenElement(seq++, "option");
                    builder.AddAttribute(seq++, "value", "");
                    builder.AddContent(seq++, $"— {Localizer["DataGrid_FilterAll"]} —");
                    builder.CloseElement();
                    foreach (var ei in enumItems)
                    {
                        builder.OpenElement(seq++, "option");
                        builder.AddAttribute(seq++, "value", ei.Name);
                        if (currentVal == ei.Name)
                            builder.AddAttribute(seq++, "selected", true);
                        builder.AddContent(seq++, ei.Label);
                        builder.CloseElement();
                    }
                    builder.CloseElement();
                    break;
                }

                case "date":
                {
                    var dateVal = NormalizeDateForInput(currentVal, false);
                    builder.OpenElement(seq++, "input");
                    builder.AddAttribute(seq++, "type", "date");
                    builder.AddAttribute(seq++, "class",
                        "sg-edit-form-input" + (hasError ? " sg-edit-invalid" : ""));
                    builder.AddAttribute(seq++, "value", dateVal);
                    builder.AddAttribute(seq++, "oninput",
                        EventCallback.Factory.Create<ChangeEventArgs>(this, e =>
                        {
                            var val = e.Value?.ToString();
                            _editFormValues[colKey] = val;
                            ApplyEditValueToItem(colKey, val);
                            ValidateEditField(colKey);
                            StateHasChanged();
                        }));
                    builder.CloseElement();
                    break;
                }

                case "datetime":
                {
                    var dtVal = NormalizeDateForInput(currentVal, true);
                    builder.OpenElement(seq++, "input");
                    builder.AddAttribute(seq++, "type", "datetime-local");
                    builder.AddAttribute(seq++, "class",
                        "sg-edit-form-input" + (hasError ? " sg-edit-invalid" : ""));
                    builder.AddAttribute(seq++, "value", dtVal);
                    builder.AddAttribute(seq++, "oninput",
                        EventCallback.Factory.Create<ChangeEventArgs>(this, e =>
                        {
                            var val = e.Value?.ToString();
                            _editFormValues[colKey] = val;
                            ApplyEditValueToItem(colKey, val);
                            ValidateEditField(colKey);
                            StateHasChanged();
                        }));
                    builder.CloseElement();
                    break;
                }

                case "number":
                {
                    builder.OpenElement(seq++, "input");
                    builder.AddAttribute(seq++, "type", "text");
                    builder.AddAttribute(seq++, "inputmode", "decimal");
                    builder.AddAttribute(seq++, "class",
                        "sg-edit-form-input" + (hasError ? " sg-edit-invalid" : ""));
                    builder.AddAttribute(seq++, "value", currentVal ?? string.Empty);
                    builder.AddAttribute(seq++, "placeholder", "0");
                    builder.AddAttribute(seq++, "oninput",
                        EventCallback.Factory.Create<ChangeEventArgs>(this, e =>
                        {
                            var val = e.Value?.ToString();
                            _editFormValues[colKey] = val;
                            ApplyEditValueToItem(colKey, val);
                            ValidateEditField(colKey);
                            StateHasChanged();
                        }));
                    builder.CloseElement();
                    break;
                }

                default:
                {
                    builder.OpenElement(seq++, "input");
                    builder.AddAttribute(seq++, "type", "text");
                    builder.AddAttribute(seq++, "class",
                        "sg-edit-form-input" + (hasError ? " sg-edit-invalid" : ""));
                    builder.AddAttribute(seq++, "value", currentVal ?? string.Empty);
                    builder.AddAttribute(seq++, "oninput",
                        EventCallback.Factory.Create<ChangeEventArgs>(this, e =>
                        {
                            var val = e.Value?.ToString();
                            _editFormValues[colKey] = val;
                            ApplyEditValueToItem(colKey, val);
                            ValidateEditField(colKey);
                            StateHasChanged();
                        }));
                    builder.CloseElement();
                    break;
                }
            }

            if (hasError)
            {
                builder.OpenElement(seq++, "span");
                builder.AddAttribute(seq++, "class", "sg-edit-form-error");
                builder.AddContent(seq++, errMsg);
                builder.CloseElement();
            }

            builder.CloseElement();
        }

        builder.CloseElement();
        builder.CloseElement();
    };

    private static string NormalizeDateForInput(string? value, bool includeTime)
    {
        if (string.IsNullOrWhiteSpace(value)) return string.Empty;
        if (!includeTime && value.Length == 10 && value[4] == '-') return value;
        if (includeTime && value.Length >= 16 && value[4] == '-') return value[..16];
        if (DateTime.TryParse(value, CultureInfo.CurrentCulture,
                System.Globalization.DateTimeStyles.None, out var dt))
        {
            return includeTime
                ? dt.ToString("yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
                : dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        }
        return value;
    }

    private void ApplyEditValueToItem(string colKey, string? value)
    {
        if (_editModalItem is null) return;
        var col = GetColumnByKey(colKey);
        if (col?.OnValueChanged is not null)
        {
            var parsed = ParseEditValue(colKey, value);
            col.OnValueChanged(_editModalItem, parsed);
            return;
        }
        var prop = typeof(TItem).GetProperty(colKey,
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance |
            System.Reflection.BindingFlags.IgnoreCase);
        if (prop is null || !prop.CanWrite) return;
        try
        {
            var parsed = ParseEditValue(colKey, value);
            if (parsed is null && Nullable.GetUnderlyingType(prop.PropertyType) is null &&
                prop.PropertyType.IsValueType)
                return;
            prop.SetValue(_editModalItem, parsed);
        }
        catch (FormatException) { }
        catch (OverflowException) { }
        catch (InvalidCastException) { }
    }

    private object? ParseEditValue(string colKey, string? value)
    {
        var col = GetColumnByKey(colKey);
        var type = col?.ValueType;
        if (type is null)
        {
            var raw = col?.GetValue(_editModalItem!);
            if (raw is not null)
                type = Nullable.GetUnderlyingType(raw.GetType()) ?? raw.GetType();
        }
        if (type is null) return value;
        return ConvertFromString(value, type);
    }

    private void ValidateEditField(string colKey)
    {
        var filterType = GetColumnFilterType(colKey);
        var val = _editFormValues.TryGetValue(colKey, out var v) ? v : null;
        _editFormErrors.Remove(colKey);

        if (filterType == "number" && !string.IsNullOrWhiteSpace(val))
        {
            var cleaned = CleanNumericString(val);
            if (!decimal.TryParse(cleaned, System.Globalization.NumberStyles.Any,
                    CultureInfo.CurrentCulture, out _) &&
                !decimal.TryParse(cleaned, System.Globalization.NumberStyles.Any,
                    CultureInfo.InvariantCulture, out _))
            {
                _editFormErrors[colKey] = Localizer["DataGrid_EditInvalidNumber"];
            }
        }
        else if (filterType == "date" && !string.IsNullOrWhiteSpace(val))
        {
            if (!DateTime.TryParse(val, CultureInfo.InvariantCulture,
                    System.Globalization.DateTimeStyles.None, out _))
                _editFormErrors[colKey] = Localizer["DataGrid_EditInvalidDate"];
        }
    }

    private async Task TrySaveEditModalAsync()
    {
        _editFormErrors.Clear();
        if (_editFormColumns is not null)
        {
            foreach (var col in _editFormColumns)
                ValidateEditField(col.Key);
        }
        if (_editFormErrors.Count > 0)
        {
            await InvokeAsync(StateHasChanged);
            return;
        }
        if (_editModalItem is not null)
            await SaveEditModal(_editModalItem);
    }

    private EventCallback<bool> CreateBooleanHandler(string key)
    {
        return EventCallback.Factory.Create<bool>(this, async (bool value) =>
        {
            await OnEditFormInputAsync(key, value);
        });
    }

    private EventCallback<DateTime?> CreateDateTimeHandler(string key)
    {
        return EventCallback.Factory.Create<DateTime?>(this, async (DateTime? value) =>
        {
            var formatted = value?.ToString("yyyy-MM-dd");
            await OnEditFormInputAsync(key, formatted);
        });
    }

    private EventCallback<decimal?> CreateDecimalHandler(string key)
    {
        return EventCallback.Factory.Create<decimal?>(this, async (decimal? value) =>
        {
            await OnEditFormInputAsync(key, value);
        });
    }

    private EventCallback<string> CreateStringHandler(string key)
    {
        return EventCallback.Factory.Create<string>(this, async (string value) =>
        {
            await OnEditFormInputAsync(key, value);
        });
    }

    private bool IsBooleanColumn(string key)
    {
        var col = GetColumnByKey(key);
        if (col?.ValueType is null)
            return false;

        var type = Nullable.GetUnderlyingType(col.ValueType) ?? col.ValueType;
        return type == typeof(bool);
    }

    private bool GetBooleanValue(string? value) => value is "true" or "True" or "1" or "✓";

    // ── Bulk edit ───────────────────────────────────────────────────────────────

    private void OpenBulkEditPicker()
    {
        _bulkEditPickerOpen = !_bulkEditPickerOpen;
    }

    private void ToggleBulkEditColumn(string key, bool selected)
    {
        if (selected) _bulkEditSelectedColumns.Add(key);
        else _bulkEditSelectedColumns.Remove(key);
    }

    private void OpenBulkEditModal()
    {
        if (_bulkEditSelectedColumns.Count == 0) return;
        _bulkEditValues.Clear();
        foreach (var key in _bulkEditSelectedColumns)
            _bulkEditValues[key] = null;
        _bulkEditPickerOpen = false;
        _bulkEditModalOpen = true;
        StateHasChanged();
    }

    private void CloseBulkEditModal()
    {
        _bulkEditModalOpen = false;
        StateHasChanged();
    }

    private async Task ConfirmBulkEditAsync()
    {
        if (!OnBulkSave.HasDelegate) return;

        var items = SelectedItems.ToList();
        var changes = new Dictionary<string, string?>(
            _bulkEditValues, StringComparer.Ordinal);

        await OnBulkSave.InvokeAsync(new SgBulkEditEventArgs<TItem>
        {
            Items = items,
            Changes = changes
        });

        _bulkEditModalOpen = false;
        _bulkEditSelectedColumns.Clear();
        _bulkEditValues.Clear();
        _itemsVersion++;
        InvalidateComputedRowsCache();
        await InvokeAsync(StateHasChanged);
    }

    private List<SgDataGridColumn<TItem>> GetBulkEditableColumns()
        => _columns.Where(c => c.Editable && c.Value is not null && !c.Hidden).ToList();

    // ── Row highlighting ────────────────────────────────────────────────────────

    internal bool MatchesRowHighlightRule(TItem item, RowHighlightRule rule)
    {
        if (!rule.IsEnabled || rule.Rules.Count == 0)
            return false;

        if (rule.RulesAnd)
        {
            foreach (var queryRule in rule.Rules)
            {
                if (!MatchesQueryRule(item, queryRule))
                    return false;
            }
            return true;
        }
        else
        {
            foreach (var queryRule in rule.Rules)
            {
                if (MatchesQueryRule(item, queryRule))
                    return true;
            }
            return false;
        }
    }

    internal RowHighlightRule? GetMatchingRowHighlightRule(TItem item)
    {
        foreach (var rule in _rowHighlightRules)
        {
            if (!string.IsNullOrEmpty(rule.TargetColumnKey)) continue;
            if (MatchesRowHighlightRule(item, rule))
                return rule;
        }
        return null;
    }

    internal RowHighlightRule? GetMatchingCellHighlightRule(TItem item, string columnKey)
    {
        foreach (var rule in _rowHighlightRules)
        {
            if (rule.TargetColumnKey == columnKey && MatchesRowHighlightRule(item, rule))
                return rule;
        }
        return null;
    }

    internal bool HasCellHighlightRules =>
        _rowHighlightRules.Any(r => r.IsEnabled && !string.IsNullOrEmpty(r.TargetColumnKey));

    public IReadOnlyList<RowHighlightRule> GetRowHighlightRules() =>
        _rowHighlightRules.Select(r => new RowHighlightRule
        {
            Id = r.Id,
            Name = r.Name,
            Rules = r.Rules.Select(CloneQueryRule).ToList(),
            RulesAnd = r.RulesAnd,
            BackgroundColor = r.BackgroundColor,
            TextColor = r.TextColor,
            IsEnabled = r.IsEnabled,
            TargetColumnKey = r.TargetColumnKey
        }).ToList();

    public async Task ApplyRowHighlightRulesAsync(IReadOnlyList<RowHighlightRule>? rules)
    {
        EnsureAutoGeneratedColumns();

        _rowHighlightRules.Clear();
        if (rules is not null)
        {
            foreach (var rule in rules)
            {
                _rowHighlightRules.Add(new RowHighlightRule
                {
                    Id = rule.Id,
                    Name = rule.Name,
                    Rules = rule.Rules.Where(IsValidQueryRule).Select(CloneQueryRule).ToList(),
                    RulesAnd = rule.RulesAnd,
                    BackgroundColor = rule.BackgroundColor,
                    TextColor = rule.TextColor,
                    IsEnabled = rule.IsEnabled,
                    TargetColumnKey = rule.TargetColumnKey
                });
            }
        }

        await SaveStateAsync();
        await InvokeAsync(StateHasChanged);
    }

    public async Task ClearRowHighlightRulesAsync()
    {
        if (_rowHighlightRules.Count == 0)
            return;

        _rowHighlightRules.Clear();
        await SaveStateAsync();
        await InvokeAsync(StateHasChanged);
    }

    private Task OpenRowHighlighterAsync()
    {
        _rowHighlighterModalOpen = true;
        StateHasChanged();
        return Task.CompletedTask;
    }

    private void CloseRowHighlighterAsync()
    {
        _rowHighlighterModalOpen = false;
        StateHasChanged();
    }

    // ── Keyboard navigation ─────────────────────────────────────────────────────

    public async Task HandleKeyDownAsync(KeyboardEventArgs e)
    {
        var rows = GetVisibleRows();
        if (rows.Count == 0) return;

        var currentIndex = _activeRow != null ? rows.IndexOf(_activeRow) : -1;

        if (e.Key == "ArrowDown")
        {
            var nextIndex = currentIndex < rows.Count - 1 ? currentIndex + 1 : 0;
            var nextRow = rows[nextIndex];

            if (e.ShiftKey && SelectionEnabled)
            {
                await HandleRangeSelectionAsync(nextRow, rows);
            }
            else
            {
                _activeRow = nextRow;
                _anchorRow = nextRow;
                await OnRowClickAsync(_activeRow);
            }
        }
        else if (e.Key == "ArrowUp")
        {
            var prevIndex = currentIndex > 0 ? currentIndex - 1 : rows.Count - 1;
            var prevRow = rows[prevIndex];

            if (e.ShiftKey && SelectionEnabled)
            {
                await HandleRangeSelectionAsync(prevRow, rows);
            }
            else
            {
                _activeRow = prevRow;
                _anchorRow = prevRow;
                await OnRowClickAsync(_activeRow);
            }
        }
        else if (e.Key == "Enter" && _activeRow != null)
        {
            await OnRowDoubleClickAsync(_activeRow);
        }
        else if (e.Key == " " && _activeRow != null && SelectionEnabled)
        {
            var shouldSelect = AllowSingleSelect ? true : !SelectedItems.Contains(_activeRow);
            await ToggleRowAsync(_activeRow, shouldSelect);
            _anchorRow = _activeRow;
        }
        else if (e.Key == "c" && e.CtrlKey)
        {
            await CopySelectionToClipboardAsync();
        }
    }

    // ── Row actions ─────────────────────────────────────────────────────────────

    private async Task OnRowClickAsync(TItem item)
    {
        _activeRow = item;
        await UpdateActiveRowInJsAsync();

        if ((DetailTemplate is not null || AutoDetail) && DetailPlacement != DetailPlacement.Inline)
        {
            switch (DetailPlacement)
            {
                case DetailPlacement.Drawer:
                    _detailItem = item;
                    _detailDrawerVisible = true;
                    _detailWindowVisible = false;
                    break;
                case DetailPlacement.Window:
                    _detailItem = item;
                    _detailWindowVisible = true;
                    _detailDrawerVisible = false;
                    break;
            }
            StateHasChanged();
        }

        if (RowClicked.HasDelegate)
            await RowClicked.InvokeAsync(item);
    }

    private async Task OnRowDoubleClickAsync(TItem item)
    {
        if (AllowEdit)
        {
            await StartEditModalAsync(item);
        }
        else if (RowDoubleClicked.HasDelegate)
        {
            await RowDoubleClicked.InvokeAsync(item);
        }
    }

    private void OnRowExpandToggle(TItem item)
    {
        if (DetailTemplate is null && !AutoDetail || DetailPlacement != DetailPlacement.Inline)
            return;

        if (!_expandedRows.Add(item))
            _expandedRows.Remove(item);

        StateHasChanged();
    }

    private bool IsActiveRow(TItem item) =>
        _activeRow is not null && EqualityComparer<TItem>.Default.Equals(_activeRow, item);

    private bool IsRowExpanded(TItem item) => _expandedRows.Contains(item);

    private void CloseDetail()
    {
        _detailDrawerVisible = false;
        _detailWindowVisible = false;
        _detailItem = default;
    }

    private async Task OnRowContextMenuInternal(MouseEventArgs args, TItem item, SgDataGridColumn<TItem>? column)
    {
        if (!OnRowContextMenu.HasDelegate)
            return;

        var payload = new SgDataGridContextMenuEventArgs<TItem>
        {
            Item = item,
            Column = column,
            ColumnKey = column?.Key,
            ColumnTitle = column?.Title,
            CellValue = column?.GetValue(item),
            FormattedValue = column?.GetDisplay(item),
            MouseArgs = args
        };

        await OnRowContextMenu.InvokeAsync(payload);
    }

    private async Task OnCellClickInternal(MouseEventArgs args, TItem item, SgDataGridColumn<TItem> column)
    {
        if (!OnCellClick.HasDelegate) return;
        await OnCellClick.InvokeAsync(new SgDataGridCellClickEventArgs<TItem>
        {
            Item = item,
            Column = column,
            ColumnKey = column.Key,
            ColumnTitle = column.Title,
            CellValue = column.GetValue(item),
            FormattedValue = column.GetDisplay(item),
            MouseArgs = args
        });
    }

    private async Task OnCellDoubleClickInternal(MouseEventArgs args, TItem item, SgDataGridColumn<TItem> column)
    {
        if (!OnCellDoubleClick.HasDelegate) return;
        await OnCellDoubleClick.InvokeAsync(new SgDataGridCellClickEventArgs<TItem>
        {
            Item = item,
            Column = column,
            ColumnKey = column.Key,
            ColumnTitle = column.Title,
            CellValue = column.GetValue(item),
            FormattedValue = column.GetDisplay(item),
            MouseArgs = args
        });
    }

    // ── Delete / Undo ───────────────────────────────────────────────────────────

    private async Task DeleteRowAsync(TItem item)
    {
        var removed = false;
        if (Items is IList<TItem> list)
        {
            var index = list.IndexOf(item);
            if (index >= 0)
            {
                list.RemoveAt(index);
                _deletedRows.Push(new DeletedRowEntry(item, index));
                removed = true;
            }
        }

        SelectedItems.Remove(item);
        _expandedRows.Remove(item);
        if (_detailItem is not null && EqualityComparer<TItem>.Default.Equals(_detailItem, item))
            CloseDetail();

        if (removed)
        {
            _itemsVersion++;
            _prevItemsCount = Items is ICollection ic ? ic.Count : _prevItemsCount;
        }

        if (RowDeleted.HasDelegate)
            await RowDeleted.InvokeAsync(item);

        _selectionVersion++;
        _selectionChangedPending = true;
        _currentPage = Math.Clamp(_currentPage, 1, TotalPages);
        InvalidateComputedRowsCache();
        await FlushSelectedItemsChangedAsync();
        await InvokeAsync(StateHasChanged);
    }

    private async Task UndoDeleteAsync()
    {
        if (_deletedRows.Count == 0 || Items is not IList<TItem> list)
            return;

        var entry = _deletedRows.Pop();
        list.Insert(Math.Clamp(entry.Index, 0, list.Count), entry.Item);
        _itemsVersion++;
        _prevItemsCount = list.Count;
        InvalidateComputedRowsCache();
        await InvokeAsync(StateHasChanged);
    }
}
