<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SuperUI.Demo</AssemblyName>
    <RootNamespace>SuperUI.Demo</RootNamespace>
    <NoWarn>$(NoWarn);SUPERUI_LANGGRAPH;CS0169;CS0414;CS0649;CS0067;CS0419;CS0618;CS8602;CS8603;CS8604;CS8605;CS8669;CS1570;CS0108;CS1998;CS1574;CS1734;CS1735;CA1416;BL0007;CS8974;CS8601;CS8629;CS8123;CS0105;RZ2012;CS8509</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperUI\SuperUI.csproj" />
  </ItemGroup>

</Project>
