using System;

namespace SuperUI.Components
{
    /// <summary>
    /// Represents a single event displayed by <see cref="SgCalendar"/>.
    /// </summary>
    public class SgCalendarEvent
    {
        /// <summary>Stable identifier. A new GUID is generated by default.</summary>
        public string Id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>Short headline shown on the chip and in the popover.</summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>Optional longer body text rendered in expanded views.</summary>
        public string? Description { get; set; }

        /// <summary>Start date of the event. Time-of-day is used together with <see cref="StartTime"/>.</summary>
        public DateTime Date { get; set; }

        /// <summary>Optional last day of a multi-day event. Inclusive — set to a later date than <see cref="Date"/>.</summary>
        public DateTime? EndDate { get; set; }

        /// <summary>Hex / CSS color for the chip. Drives the heat tint and accent.</summary>
        public string? Color { get; set; }

        /// <summary>Optional emoji or single-character glyph rendered next to the title.</summary>
        public string? Icon { get; set; }

        /// <summary>True when the event spans the whole day(s).</summary>
        public bool IsAllDay { get; set; } = true;

        /// <summary>Start time-of-day for timed events.</summary>
        public TimeSpan? StartTime { get; set; }

        /// <summary>End time-of-day for timed events.</summary>
        public TimeSpan? EndTime { get; set; }

        /// <summary>iCal-style recurrence rule (e.g. "FREQ=WEEKLY;BYDAY=MO,WE,FR").</summary>
        public string? RecurrenceRule { get; set; }

        /// <summary>Optional location text rendered under the title.</summary>
        public string? Location { get; set; }

        /// <summary>Optional priority. Higher values render the urgent indicator.</summary>
        public SgCalendarEventPriority Priority { get; set; } = SgCalendarEventPriority.Normal;

        /// <summary>Workflow status of the event.</summary>
        public SgCalendarEventStatus Status { get; set; } = SgCalendarEventStatus.Confirmed;

        /// <summary>Optional URL associated with the event (used as link in details).</summary>
        public string? Url { get; set; }

        /// <summary>Optional tag/category label rendered as a soft pill.</summary>
        public string? Category { get; set; }

        /// <summary>When true, the event cannot be edited or dragged.</summary>
        public bool IsReadOnly { get; set; }
    }

    /// <summary>Workflow state for <see cref="SgCalendarEvent"/>.</summary>
    public enum SgCalendarEventStatus
    {
        /// <summary>The event is confirmed and rendered with full intensity.</summary>
        Confirmed,
        /// <summary>The event is tentatively scheduled and rendered with reduced opacity / hatched border.</summary>
        Tentative,
        /// <summary>The event was cancelled — rendered struck-through and dimmed.</summary>
        Cancelled
    }

    /// <summary>Priority hint for <see cref="SgCalendarEvent"/>.</summary>
    public enum SgCalendarEventPriority
    {
        /// <summary>No special treatment.</summary>
        Normal,
        /// <summary>Renders an "important" pip on the chip.</summary>
        High,
        /// <summary>Renders a stronger urgent pip on the chip.</summary>
        Urgent
    }
}
