using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace SuperUI.Components;

public partial class SgTable<TItem> : ComponentBase
{
    private readonly List<SgTableColumn<TItem>> _columns = new();
    private readonly List<SgTableColumn<TItem>> _autoGeneratedColumns = new();
    private bool _autoColumnsGenerated;
    private string? _searchText;
    private string? _sortColumnKey;
    private SortDirection _sortDirection = SortDirection.None;
    private int _pageNumber = 1;
    private readonly HashSet<TItem> _selectedItems = new();
    private bool _selectAll;

    [Parameter] public IEnumerable<TItem>? Items { get; set; }
    [Parameter] public RenderFragment? ChildContent { get; set; }
    [Parameter] public string? Title { get; set; }
    [Parameter] public bool ShowSearch { get; set; } = true;
    [Parameter] public string? CssClass { get; set; }
    [Parameter] public bool FullWidth { get; set; }
    [Parameter] public string? EmptyText { get; set; }
    [Parameter] public bool AutoGenerateColumns { get; set; }
    [Parameter] public Func<TItem, string?>? RowClass { get; set; }
    [Parameter] public Func<TItem, string?>? RowStyle { get; set; }
    [Parameter] public bool ShowRowNumbers { get; set; }
    [Parameter] public bool EnablePaging { get; set; }
    [Parameter] public int PageSize { get; set; } = 20;
    [Parameter] public bool AllowSelection { get; set; }
    [Parameter] public bool AllowMultiSelect { get; set; }
    [Parameter] public List<TItem> SelectedItems { get; set; } = new();
    [Parameter] public EventCallback<List<TItem>> SelectedItemsChanged { get; set; }
    [Parameter] public EventCallback<TItem> RowClicked { get; set; }
    [Parameter] public EventCallback<TItem> RowDoubleClicked { get; set; }

    internal IReadOnlyList<SgTableColumn<TItem>> Columns
    {
        get
        {
            EnsureAutoGeneratedColumns();
            return _columns.Count > 0 ? _columns : _autoGeneratedColumns;
        }
    }

    private void EnsureAutoGeneratedColumns()
    {
        if (!AutoGenerateColumns) return;
        if (_autoColumnsGenerated) return;

        var itemType = typeof(TItem);
        var properties = itemType.GetProperties(BindingFlags.Public | BindingFlags.Instance);

        foreach (var prop in properties)
        {
            var displayAttr = prop.GetCustomAttribute<DisplayAttribute>();
            var displayNameAttr = prop.GetCustomAttribute<DisplayNameAttribute>();
            var browseAttr = prop.GetCustomAttribute<BrowsableAttribute>();

            if (browseAttr != null && !browseAttr.Browsable)
                continue;

            var title = displayAttr?.Name ?? displayNameAttr?.DisplayName ?? prop.Name;
            var key = prop.Name;

            var column = SgTableColumn<TItem>.CreateSynthetic(
                key,
                title,
                item => prop.GetValue(item),
                true,
                prop.PropertyType
            );

            _autoGeneratedColumns.Add(column);
        }

        _autoColumnsGenerated = true;
    }

    internal int TotalCount => FilteredAndSortedItems.Count();
    internal int TotalPages => Math.Max(1, (int)Math.Ceiling((double)TotalCount / PageSize));
    internal int CurrentPage
    {
        get => _pageNumber;
        set
        {
            _pageNumber = Math.Max(1, Math.Min(value, TotalPages));
        }
    }
    internal List<TItem> FilteredAndSortedItems
    {
        get
        {
            if (Items == null) return new List<TItem>();
            var filtered = Items;
            if (!string.IsNullOrWhiteSpace(_searchText))
            {
                var search = _searchText.Trim().ToLowerInvariant();
                var cols = Columns;
                filtered = filtered.Where(item =>
                {
                    foreach (var col in cols)
                    {
                        var display = col.GetDisplay(item);
                        if (display.ToLowerInvariant().Contains(search))
                            return true;
                    }
                    return false;
                });
            }
            if (!string.IsNullOrWhiteSpace(_sortColumnKey))
            {
                var cols = Columns;
                var col = cols.FirstOrDefault(c => c.Key == _sortColumnKey);
                if (col != null)
                {
                    filtered = _sortDirection == SortDirection.Ascending
                        ? filtered.OrderBy(item => col.GetValue(item))
                        : filtered.OrderByDescending(item => col.GetValue(item));
                }
            }
            return filtered.ToList();
        }
    }
    internal IEnumerable<TItem> PagedItems
    {
        get
        {
            if (!EnablePaging) return FilteredAndSortedItems;
            return FilteredAndSortedItems.Skip((CurrentPage - 1) * PageSize).Take(PageSize);
        }
    }

    internal string EffectiveEmptyText => string.IsNullOrWhiteSpace(EmptyText) ? "Нет данных" : EmptyText!;

    internal void RegisterColumn(SgTableColumn<TItem> column)
    {
        if (!_columns.Contains(column))
        {
            _columns.Add(column);
        }
    }

    internal void UnregisterColumn(SgTableColumn<TItem> column)
    {
        _columns.Remove(column);
    }

    private void OnSearchInput(ChangeEventArgs e)
    {
        _searchText = e.Value?.ToString();
    }

    private void OnSortClick(string columnKey)
    {
        if (_sortColumnKey == columnKey)
        {
            _sortDirection = _sortDirection switch
            {
                SortDirection.None => SortDirection.Ascending,
                SortDirection.Ascending => SortDirection.Descending,
                SortDirection.Descending => SortDirection.None,
                _ => SortDirection.None
            };
            if (_sortDirection == SortDirection.None)
                _sortColumnKey = null;
        }
        else
        {
            _sortColumnKey = columnKey;
            _sortDirection = SortDirection.Ascending;
        }
    }

    internal bool IsSelected(TItem item) => _selectedItems.Contains(item);

    internal async Task ToggleSelection(TItem item)
    {
        if (!AllowSelection) return;
        if (AllowMultiSelect)
        {
            if (_selectedItems.Contains(item))
                _selectedItems.Remove(item);
            else
                _selectedItems.Add(item);
        }
        else
        {
            _selectedItems.Clear();
            _selectedItems.Add(item);
        }
        SelectedItems = _selectedItems.ToList();
        await SelectedItemsChanged.InvokeAsync(SelectedItems);
    }

    internal async Task ToggleSelectAll()
    {
        if (!AllowSelection || !AllowMultiSelect) return;
        _selectAll = !_selectAll;
        if (_selectAll)
        {
            foreach (var item in PagedItems)
                _selectedItems.Add(item);
        }
        else
        {
            foreach (var item in PagedItems)
                _selectedItems.Remove(item);
        }
        SelectedItems = _selectedItems.ToList();
        await SelectedItemsChanged.InvokeAsync(SelectedItems);
    }

    internal async Task OnRowClick(TItem item)
    {
        if (RowClicked.HasDelegate)
            await RowClicked.InvokeAsync(item);
    }

    internal async Task OnRowDoubleClick(TItem item)
    {
        if (RowDoubleClicked.HasDelegate)
            await RowDoubleClicked.InvokeAsync(item);
    }
}
