using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.JSInterop;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text;
using SuperUI.Enums;

namespace SuperUI.Components;

public partial class SgTable<TItem> : ComponentBase
{
    private readonly List<SgTableColumn<TItem>> _columns = new();
    private readonly List<SgTableColumn<TItem>> _autoGeneratedColumns = new();
    private bool _autoColumnsGenerated;
    private string? _searchText;
    private string? _sortColumnKey;
    private SgDataGridSortDirection _sortDirection = SgDataGridSortDirection.None;
    private int _pageNumber = 1;
    private readonly HashSet<TItem> _selectedItems = new();
    private bool _selectAll;
    private ElementReference _tableRef;
    private ElementReference _headerScrollRef;
    private ElementReference _bodyScrollRef;
    private IJSObjectReference? _jsModule;
    private Dictionary<string, double> _columnWidths = new();
    private string? _resizingColumn;
    private double _resizeStartX;
    private double _resizeStartWidth;
    private int? _draggedColumnIndex;
    private int? _dropTargetIndex;
    private List<SgTableHeaderGroup<TItem>> _headerGroups = new();
    private bool _showExportMenu;
    private ElementReference _exportRef;

    [Inject] private IJSRuntime JS { get; set; } = default!;

    [Parameter] public bool Loading { get; set; }
    [Parameter] public IEnumerable<TItem>? Items { get; set; }
    [Parameter] public RenderFragment? ChildContent { get; set; }
    [Parameter] public string? Title { get; set; }
    [Parameter] public bool ShowSearch { get; set; } = true;
    [Parameter] public string? SearchPlaceholder { get; set; }
    [Parameter] public string? CssClass { get; set; }
    [Parameter] public string? Height { get; set; }
    [Parameter] public string MaxHeight { get; set; } = "70vh";
    [Parameter] public bool FullWidth { get; set; }
    [Parameter] public string? EmptyText { get; set; }
    [Parameter] public bool AutoGenerateColumns { get; set; }
    [Parameter] public Func<TItem, string?>? RowClass { get; set; }
    [Parameter] public Func<TItem, string?>? RowStyle { get; set; }
    [Parameter] public bool ShowRowNumbers { get; set; }
    [Parameter] public bool EnablePaging { get; set; }
    [Parameter] public int PageSize { get; set; } = 20;
    [Parameter] public EventCallback<int> PageSizeChanged { get; set; }
    [Parameter] public int PageNumber { get; set; } = 1;
    [Parameter] public EventCallback<int> PageNumberChanged { get; set; }
    [Parameter] public bool AllowSelection { get; set; }
    [Parameter] public bool AllowMultiSelect { get; set; }
    [Parameter] public List<TItem> SelectedItems { get; set; } = new();
    [Parameter] public EventCallback<List<TItem>> SelectedItemsChanged { get; set; }
    [Parameter] public EventCallback<TItem> RowClicked { get; set; }
    [Parameter] public EventCallback<TItem> RowDoubleClicked { get; set; }
    [Parameter] public bool ShowExport { get; set; }
    [Parameter] public bool ShowExportCsv { get; set; }
    [Parameter] public bool ShowExportExcel { get; set; }
    [Parameter] public bool AllowPageSizeChange { get; set; }
    [Parameter] public int[] PageSizeOptions { get; set; } = new[] { 10, 20, 50, 100 };
    [Parameter] public bool AllowColumnResize { get; set; } = true;
    [Parameter] public bool AllowColumnReorder { get; set; } = true;

    internal List<SgTableHeaderGroup<TItem>> HeaderGroups => _headerGroups;

    internal IReadOnlyList<SgTableColumn<TItem>> Columns
    {
        get
        {
            EnsureAutoGeneratedColumns();
            return _columns.Count > 0 ? _columns : _autoGeneratedColumns;
        }
    }

    private void EnsureAutoGeneratedColumns()
    {
        if (!AutoGenerateColumns) return;
        if (_autoColumnsGenerated) return;

        var itemType = typeof(TItem);
        var properties = itemType.GetProperties(BindingFlags.Public | BindingFlags.Instance);

        foreach (var prop in properties)
        {
            var displayAttr = prop.GetCustomAttribute<DisplayAttribute>();
            var displayNameAttr = prop.GetCustomAttribute<DisplayNameAttribute>();
            var browseAttr = prop.GetCustomAttribute<BrowsableAttribute>();

            if (browseAttr != null && !browseAttr.Browsable)
                continue;

            var title = displayAttr?.Name ?? displayNameAttr?.DisplayName ?? prop.Name;
            var key = prop.Name;

            var column = SgTableColumn<TItem>.CreateSynthetic(
                key,
                title,
                item => prop.GetValue(item),
                true,
                prop.PropertyType
            );

            _autoGeneratedColumns.Add(column);
        }

        _autoColumnsGenerated = true;
    }

    internal int TotalCount => FilteredAndSortedItems.Count();
    internal int TotalPages => Math.Max(1, (int)Math.Ceiling((double)TotalCount / PageSize));
    internal int CurrentPage
    {
        get
        {
            var page = PageNumber > 0 ? PageNumber : _pageNumber;
            return Math.Max(1, Math.Min(page, TotalPages));
        }
    }

    private async Task GoToPage(int page)
    {
        var targetPage = Math.Max(1, Math.Min(page, TotalPages));
        _pageNumber = targetPage;
        PageNumber = targetPage;
        
        if (PageNumberChanged.HasDelegate)
            await PageNumberChanged.InvokeAsync(targetPage);
            
        StateHasChanged();
    }

    internal List<TItem> FilteredAndSortedItems
    {
        get
        {
            if (Items == null) return new List<TItem>();
            var filtered = Items;
            if (!string.IsNullOrWhiteSpace(_searchText))
            {
                var search = _searchText.Trim().ToLowerInvariant();
                var cols = Columns;
                filtered = filtered.Where(item =>
                {
                    foreach (var col in cols)
                    {
                        var display = col.GetDisplay(item);
                        if (display.ToLowerInvariant().Contains(search))
                            return true;
                    }
                    return false;
                });
            }
            if (!string.IsNullOrWhiteSpace(_sortColumnKey))
            {
                var cols = Columns;
                var col = cols.FirstOrDefault(c => c.Key == _sortColumnKey);
                if (col != null)
                {
                    filtered =                     _sortDirection == SgDataGridSortDirection.Ascending
                        ? filtered.OrderBy(item => col.GetValue(item))
                        : filtered.OrderByDescending(item => col.GetValue(item));
                }
            }
            return filtered.ToList();
        }
    }
    internal IEnumerable<TItem> PagedItems
    {
        get
        {
            if (!EnablePaging) return FilteredAndSortedItems;
            return FilteredAndSortedItems.Skip((CurrentPage - 1) * PageSize).Take(PageSize);
        }
    }

    internal string EffectiveEmptyText => string.IsNullOrWhiteSpace(EmptyText) ? "Нет данных" : EmptyText!;

    internal void RegisterColumn(SgTableColumn<TItem> column)
    {
        if (!_columns.Contains(column))
        {
            _columns.Add(column);
            StateHasChanged();
        }
    }

    internal void UnregisterColumn(SgTableColumn<TItem> column)
    {
        _columns.Remove(column);
    }

    internal void RegisterHeaderGroup(SgTableHeaderGroup<TItem> group)
    {
        if (!_headerGroups.Contains(group))
        {
            _headerGroups.Add(group);
            StateHasChanged();
        }
    }

    internal void UnregisterHeaderGroup(SgTableHeaderGroup<TItem> group)
    {
        _headerGroups.Remove(group);
    }

    private async Task OnBodyScroll()
    {
        try
        {
            _jsModule ??= await JS.InvokeAsync<IJSObjectReference>(
                "import", "./_content/SuperUI/Components/SgTable.razor.js");
            await _jsModule.InvokeVoidAsync("syncHeaderScroll", _headerScrollRef, _bodyScrollRef);
        }
        catch { }
    }

    // Column resize
    private async Task OnResizeStart(MouseEventArgs e, string columnKey)
    {
        _resizingColumn = columnKey;
        _resizeStartX = e.ClientX;
        
        var col = Columns.FirstOrDefault(c => c.Key == columnKey);
        if (col != null)
        {
            if (_columnWidths.ContainsKey(columnKey))
            {
                _resizeStartWidth = _columnWidths[columnKey];
            }
            else if (!string.IsNullOrEmpty(col.Width) && col.Width.EndsWith("px"))
            {
                _resizeStartWidth = double.Parse(col.Width.Replace("px", ""));
            }
            else
            {
                _resizeStartWidth = 150; // default width
            }
        }

        await JS.InvokeVoidAsync("eval", @"
            document.body.style.cursor = 'col-resize';
            document.body.style.userSelect = 'none';
            const onMouseMove = (e) => {
                window.sgTableResizeEvent = e;
            };
            const onMouseUp = () => {
                document.body.style.cursor = '';
                document.body.style.userSelect = '';
                document.removeEventListener('mousemove', onMouseMove);
                document.removeEventListener('mouseup', onMouseUp);
                window.sgTableResizeEnd = true;
            };
            document.addEventListener('mousemove', onMouseMove);
            document.addEventListener('mouseup', onMouseUp);
        ");
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (_resizingColumn != null)
        {
            try
            {
                var resizeEvent = await JS.InvokeAsync<MouseEventArgs?>("eval", "window.sgTableResizeEvent");
                if (resizeEvent != null)
                {
                    var delta = resizeEvent.ClientX - _resizeStartX;
                    var newWidth = Math.Max(50, _resizeStartWidth + delta);
                    _columnWidths[_resizingColumn] = newWidth;
                    StateHasChanged();
                    await JS.InvokeVoidAsync("eval", "window.sgTableResizeEvent = null");
                }

                var resizeEnd = await JS.InvokeAsync<bool>("eval", "window.sgTableResizeEnd || false");
                if (resizeEnd)
                {
                    _resizingColumn = null;
                    await JS.InvokeVoidAsync("eval", "window.sgTableResizeEnd = false");
                }
            }
            catch
            {
                // Ignore JS interop errors
            }
        }
    }

    // Column drag and drop
    private void OnColumnDragStart(int columnIndex)
    {
        if (!AllowColumnReorder) return;
        _draggedColumnIndex = columnIndex;
        StateHasChanged();
    }

    private void OnColumnDragOver(int columnIndex)
    {
        if (!AllowColumnReorder || _draggedColumnIndex == null) return;
        if (_dropTargetIndex != columnIndex)
        {
            _dropTargetIndex = columnIndex;
            StateHasChanged();
        }
    }

    private void OnColumnDrop(int columnIndex)
    {
        if (!AllowColumnReorder || _draggedColumnIndex == null || _draggedColumnIndex == columnIndex)
        {
            _draggedColumnIndex = null;
            _dropTargetIndex = null;
            StateHasChanged();
            return;
        }

        var draggedCol = _columns[_draggedColumnIndex.Value];
        _columns.RemoveAt(_draggedColumnIndex.Value);
        
        // Adjust index if dragging from left to right
        var insertIndex = _draggedColumnIndex.Value < columnIndex ? columnIndex - 1 : columnIndex;
        _columns.Insert(insertIndex, draggedCol);

        _draggedColumnIndex = null;
        _dropTargetIndex = null;
        StateHasChanged();
    }

    private void OnColumnDragEnd()
    {
        _draggedColumnIndex = null;
        _dropTargetIndex = null;
        StateHasChanged();
    }

    private void OnSearchInput(ChangeEventArgs e)
    {
        _searchText = e.Value?.ToString();
    }

    private async Task OnSearchChange(ChangeEventArgs e)
    {
        _searchText = e.Value?.ToString();
        await GoToPage(1);
    }

    private async Task OnSortClick(string columnKey)
    {
        if (_sortColumnKey == columnKey)
        {
            _sortDirection = _sortDirection switch
            {
                SgDataGridSortDirection.None => SgDataGridSortDirection.Ascending,
                SgDataGridSortDirection.Ascending => SgDataGridSortDirection.Descending,
                SgDataGridSortDirection.Descending => SgDataGridSortDirection.None,
                _ => SgDataGridSortDirection.None
            };
            if (_sortDirection == SgDataGridSortDirection.None)
                _sortColumnKey = null;
        }
        else
        {
            _sortColumnKey = columnKey;
            _sortDirection = SgDataGridSortDirection.Ascending;
        }
        
        await GoToPage(1); // Reset to first page when sort changes
    }

    private async Task OnPageSizeChange(ChangeEventArgs e)
    {
        if (int.TryParse(e.Value?.ToString(), out var newSize))
        {
            await HandlePageSizeChange(newSize);
        }
    }

    private async Task HandlePageSizeChange(int newSize)
    {
        PageSize = newSize;
        if (PageSizeChanged.HasDelegate)
            await PageSizeChanged.InvokeAsync(PageSize);
            
        await GoToPage(1); // Reset to first page
    }

    private async Task GoToFirstPage()
    {
        await GoToPage(1);
    }

    private async Task GoToPreviousPage()
    {
        await GoToPage(CurrentPage - 1);
    }

    private async Task GoToNextPage()
    {
        await GoToPage(CurrentPage + 1);
    }

    private async Task GoToLastPage()
    {
        await GoToPage(TotalPages);
    }

    internal bool IsSelected(TItem item) => _selectedItems.Contains(item);

    internal async Task ToggleSelection(TItem item)
    {
        if (!AllowSelection) return;
        if (AllowMultiSelect)
        {
            if (_selectedItems.Contains(item))
                _selectedItems.Remove(item);
            else
                _selectedItems.Add(item);
        }
        else
        {
            _selectedItems.Clear();
            _selectedItems.Add(item);
        }
        SelectedItems = _selectedItems.ToList();
        await SelectedItemsChanged.InvokeAsync(SelectedItems);
    }

    internal async Task ToggleSelectAll()
    {
        if (!AllowSelection || !AllowMultiSelect) return;
        _selectAll = !_selectAll;
        if (_selectAll)
        {
            foreach (var item in PagedItems)
                _selectedItems.Add(item);
        }
        else
        {
            foreach (var item in PagedItems)
                _selectedItems.Remove(item);
        }
        SelectedItems = _selectedItems.ToList();
        await SelectedItemsChanged.InvokeAsync(SelectedItems);
    }

    internal async Task OnRowClick(TItem item)
    {
        if (RowClicked.HasDelegate)
            await RowClicked.InvokeAsync(item);
    }

    internal async Task OnRowDoubleClick(TItem item)
    {
        if (RowDoubleClicked.HasDelegate)
            await RowDoubleClicked.InvokeAsync(item);
    }

    private async Task ExportToCsv()
    {
        _showExportMenu = false;
        var csv = new StringBuilder();
        var cols = Columns.ToList();

        // Header
        csv.AppendLine(string.Join(",", cols.Select(c => EscapeCsv(c.Title))));

        // Rows
        foreach (var item in FilteredAndSortedItems)
        {
            var values = cols.Select(c => EscapeCsv(c.GetDisplay(item)));
            csv.AppendLine(string.Join(",", values));
        }

        var fileName = $"{Title ?? "export"}_{DateTime.Now:yyyyMMdd_HHmmss}.csv";
        var content = csv.ToString();
        
        // Add UTF-8 BOM for Excel to recognize Cyrillic
        var bom = new byte[] { 0xEF, 0xBB, 0xBF };
        var bytes = Encoding.UTF8.GetBytes(content);
        var finalBytes = new byte[bom.Length + bytes.Length];
        Buffer.BlockCopy(bom, 0, finalBytes, 0, bom.Length);
        Buffer.BlockCopy(bytes, 0, finalBytes, bom.Length, bytes.Length);
        
        var base64 = Convert.ToBase64String(finalBytes);

        await JS.InvokeVoidAsync("eval", $@"
            (function() {{
                const base64 = '{base64}';
                const binary = atob(base64);
                const len = binary.length;
                const bytes = new Uint8Array(len);
                for (let i = 0; i < len; i++) {{
                    bytes[i] = binary.charCodeAt(i);
                }}
                const blob = new Blob([bytes], {{ type: 'text/csv;charset=utf-8;' }});
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = '{fileName}';
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(url);
            }})();
        ");
    }

    private async Task ExportToExcel()
    {
        _showExportMenu = false;
        var sb = new StringBuilder();
        var cols = Columns.ToList();

        sb.AppendLine("<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>");
        sb.AppendLine("<head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'></head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<table border='1'>");
        
        // Header
        sb.AppendLine("  <thead>");
        sb.AppendLine("    <tr style='background-color: #f2f2f2;'>");
        foreach (var col in cols)
        {
            sb.AppendLine($"      <th>{System.Net.WebUtility.HtmlEncode(col.Title)}</th>");
        }
        sb.AppendLine("    </tr>");
        sb.AppendLine("  </thead>");

        // Body
        sb.AppendLine("  <tbody>");
        foreach (var item in FilteredAndSortedItems)
        {
            sb.AppendLine("    <tr>");
            foreach (var col in cols)
            {
                var val = col.GetDisplay(item);
                sb.AppendLine($"      <td>{System.Net.WebUtility.HtmlEncode(val)}</td>");
            }
            sb.AppendLine("    </tr>");
        }
        sb.AppendLine("  </tbody>");
        sb.AppendLine("</table>");
        sb.AppendLine("</body></html>");

        var fileName = $"{Title ?? "export"}_{DateTime.Now:yyyyMMdd_HHmmss}.xls";
        var content = sb.ToString();

        // Add UTF-8 BOM
        var bom = new byte[] { 0xEF, 0xBB, 0xBF };
        var bytes = Encoding.UTF8.GetBytes(content);
        var finalBytes = new byte[bom.Length + bytes.Length];
        Buffer.BlockCopy(bom, 0, finalBytes, 0, bom.Length);
        Buffer.BlockCopy(bytes, 0, finalBytes, bom.Length, bytes.Length);

        var base64 = Convert.ToBase64String(finalBytes);

        await JS.InvokeVoidAsync("eval", $@"
            (function() {{
                const base64 = '{base64}';
                const binary = atob(base64);
                const len = binary.length;
                const bytes = new Uint8Array(len);
                for (let i = 0; i < len; i++) {{
                    bytes[i] = binary.charCodeAt(i);
                }}
                const blob = new Blob([bytes], {{ type: 'application/vnd.ms-excel' }});
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = '{fileName}';
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(url);
            }})();
        ");
    }

    private void ToggleExportMenu()
    {
        _showExportMenu = !_showExportMenu;
    }

    private void HandleExportFocusOut()
    {
        // Delay to allow button click to process before hiding menu
        _ = Task.Delay(200).ContinueWith(_ => 
        {
            _showExportMenu = false;
            InvokeAsync(StateHasChanged);
        });
    }

    private static string EscapeCsv(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        if (value.Contains(',') || value.Contains('"') || value.Contains('\n'))
        {
            return $"\"{value.Replace("\"", "\"\"")}\"";
        }
        return value;
    }
}
