using System.Text.Json;
using System.Text.Json.Nodes;
using SuperUI.Themes;

namespace ThemeDarkGenerator;

/// <summary>
/// One-shot tool: reads each "Modern" theme JSON in SuperUI/Themes/json/ and injects
/// a "dark" block generated by the brand-consistent triadic +120° pattern
/// (or the canonical palette for the 3 special themes).
///
/// 17 themes — auto-derived (H_dark = (H_light + 120) mod 360).
/// 3 themes  — hand-tuned canonical palettes (Dracula, Gruvbox, Catppuccin).
///
/// Idempotent: skips themes that already have a "dark" block.
/// </summary>
public static class Program
{
    private const string ThemesDir = @"C:\Users\SuperComp\Documents\Blazor\SuperUI.Blazor\SuperUI\Themes\json";

    // 3 special themes: id → (display name, primary hue, base bg, base fg, primary default)
    private static readonly Dictionary<string, (string name, double hue, string bg, string fg, string primary)> Specials = new()
    {
        ["dracula-dusk"] = ("Dracula Dusk",   290, "oklch(0.22 0.02 290)",   "oklch(0.93 0.015 290)",  "oklch(0.70 0.18 290)"),
        ["gruvbox-amber"] = ("Gruvbox Amber",  50, "oklch(0.18 0.015 50)",   "oklch(0.90 0.04 70)",    "oklch(0.78 0.16 65)"),
        ["catppuccin-mocha"] = ("Catppuccin Mocha", 280, "oklch(0.18 0.02 280)", "oklch(0.88 0.04 280)", "oklch(0.74 0.13 320)"),
    };

    public static int Main()
    {
        var files = Directory.GetFiles(ThemesDir, "*.json")
            .Where(f => IsModernTheme(f))
            .OrderBy(f => Path.GetFileName(f))
            .ToArray();

        Console.WriteLine($"Found {files.Length} Modern theme files.\n");

        var autoCount = 0;
        var specialCount = 0;
        var skippedCount = 0;

        foreach (var file in files)
        {
            var id = Path.GetFileNameWithoutExtension(file);

            // Parse JSON.
            var text = File.ReadAllText(file);
            var root = JsonNode.Parse(text)!;

            // Skip if dark block already exists.
            if (root["dark"] != null)
            {
                Console.WriteLine($"  [skip]  {id,-25} already has dark block");
                skippedCount++;
                continue;
            }

            // Extract light hue from "primitives.primary.N500" (e.g., "oklch(0.55 0.22 153)").
            var lightHue = ExtractPrimaryHue(root);
            if (lightHue == null)
            {
                Console.WriteLine($"  [ERROR] {id,-25} could not extract primary hue");
                continue;
            }

            // Build dark block.
            JsonObject dark;
            if (Specials.TryGetValue(id, out var spec))
            {
                dark = BuildSpecialDark(root, spec);
                specialCount++;
                Console.WriteLine($"  [special] {id,-25} lightH={lightHue,5:F1}  canonical palette");
            }
            else
            {
                var darkHue = (lightHue.Value + 120) % 360;
                dark = BuildAutoDark(root, darkHue);
                autoCount++;
                Console.WriteLine($"  [auto]    {id,-25} lightH={lightHue,5:F1} → darkH={darkHue,5:F1}");
            }

            root["dark"] = dark;

            // Write back with 2-space indent.
            var options = new JsonSerializerOptions { WriteIndented = true };
            File.WriteAllText(file, root.ToJsonString(options) + "\n");
        }

        Console.WriteLine();
        Console.WriteLine($"Done. Auto: {autoCount}  Special: {specialCount}  Skipped: {skippedCount}");
        return 0;
    }

    private static bool IsModernTheme(string filePath)
    {
        try
        {
            var text = File.ReadAllText(filePath);
            return text.Contains("\"category\": \"Modern\"");
        }
        catch
        {
            return false;
        }
    }

    private static double? ExtractPrimaryHue(JsonNode root)
    {
        // Try primitives.primary.500
        var n500 = root["primitives"]?["primary"]?["500"]?.GetValue<string>();
        if (n500 != null) return ParseHue(n500);

        // Fall back to primitives.Primary500 (uppercase variant)
        n500 = root["primitives"]?["Primary500"]?.GetValue<string>();
        if (n500 != null) return ParseHue(n500);

        return null;
    }

    private static double? ParseHue(string oklch)
    {
        // oklch(L C H) — extract last number
        var match = System.Text.RegularExpressions.Regex.Match(oklch, @"oklch\(\s*[\d.]+\s+[\d.]+\s+([\d.]+)");
        if (match.Success && double.TryParse(match.Groups[1].Value, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var h))
            return h;
        return null;
    }

    private static JsonObject BuildAutoDark(JsonNode root, double darkHue)
    {
        var dh = darkHue.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture);
        var H = dh; // for replacement

        var dark = new JsonObject
        {
            ["bg"] = new JsonObject
            {
                ["default"]    = $"oklch(0.11 0.008 {H})",
                ["subtle"]     = $"oklch(0.15 0.010 {H})",
                ["muted"]      = $"oklch(0.18 0.012 {H})",
                ["emphasized"] = $"oklch(0.22 0.014 {H})",
                ["overlay"]    = "oklch(0 0 0 / 0.72)",
                ["glass"]      = $"oklch(0.11 0.008 {H} / 0.7)"
            },
            ["surface"] = new JsonObject
            {
                ["default"] = $"oklch(0.16 0.012 {H})",
                ["raised"]  = $"oklch(0.20 0.014 {H})",
                ["overlay"] = $"oklch(0.24 0.016 {H})"
            },
            ["fg"] = new JsonObject
            {
                ["default"]   = $"oklch(0.95 0.005 {H})",
                ["subtle"]    = $"oklch(0.82 0.008 {H})",
                ["muted"]     = $"oklch(0.65 0.010 {H})",
                ["disabled"]  = $"oklch(0.55 0.010 {H})",
                ["inverse"]   = $"oklch(0.11 0.008 {H})",
                ["link"]      = $"oklch(0.65 0.20 {H})",
                ["linkHover"] = $"oklch(0.70 0.18 {H})"
            },
            ["border"] = new JsonObject
            {
                ["default"] = $"oklch(0.25 0.016 {H})",
                ["subtle"]  = $"oklch(0.18 0.012 {H})",
                ["strong"]  = $"oklch(0.32 0.018 {H})",
                ["focus"]   = $"oklch(0.65 0.20 {H})"
            },
            ["divider"] = $"oklch(0.18 0.012 {H})",
            ["colorPrimary"] = new JsonObject
            {
                ["default"] = $"oklch(0.65 0.22 {H})",
                ["subtle"]  = $"oklch(0.22 0.06 {H})",
                ["hover"]   = $"oklch(0.70 0.22 {H})",
                ["fg"]      = $"oklch(0.11 0.008 {H})"
            },
            ["colorSuccess"] = new JsonObject
            {
                ["default"] = "oklch(0.65 0.18 153)",
                ["subtle"]  = "oklch(0.22 0.05 153)",
                ["hover"]   = "oklch(0.70 0.18 153)",
                ["fg"]      = "oklch(0.11 0.008 " + H + ")"
            },
            ["colorDanger"] = new JsonObject
            {
                ["default"] = "oklch(0.62 0.22 19)",
                ["subtle"]  = "oklch(0.24 0.06 19)",
                ["hover"]   = "oklch(0.68 0.22 19)",
                ["fg"]      = "oklch(0.11 0.008 " + H + ")"
            },
            ["colorWarning"] = new JsonObject
            {
                ["default"] = "oklch(0.74 0.16 75)",
                ["subtle"]  = "oklch(0.26 0.05 75)",
                ["hover"]   = "oklch(0.80 0.14 75)",
                ["fg"]      = $"oklch(0.11 0.008 {H})"
            },
            ["colorInfo"] = new JsonObject
            {
                ["default"] = "oklch(0.62 0.15 254)",
                ["subtle"]  = "oklch(0.22 0.05 254)",
                ["hover"]   = "oklch(0.68 0.14 254)",
                ["fg"]      = "oklch(0.11 0.008 " + H + ")"
            },
            ["font"] = DeepClone(root["light"]?["font"]) ?? new JsonObject
            {
                ["default"] = "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
                ["mono"]    = "'JetBrains Mono', ui-monospace, monospace"
            },
            ["text"]       = DeepClone(root["light"]?["text"])!,
            ["fontWeight"] = DeepClone(root["light"]?["fontWeight"])!,
            ["lineHeight"] = DeepClone(root["light"]?["lineHeight"])!,
            ["shadow"] = new JsonObject
            {
                ["xs"] = "0 1px 2px 0 oklch(0 0 0 / 0.40)",
                ["sm"] = "0 2px 4px -1px oklch(0 0 0 / 0.50)",
                ["md"] = "0 4px 12px -2px oklch(0 0 0 / 0.55)",
                ["lg"] = "0 8px 24px -4px oklch(0 0 0 / 0.60)",
                ["xl"] = "0 16px 48px -8px oklch(0 0 0 / 0.65)"
            },
            ["radius"]     = DeepClone(root["light"]?["radius"])!,
            ["transition"] = DeepClone(root["light"]?["transition"])!,
            ["focusRing"]  = DeepClone(root["light"]?["focusRing"])!,
            ["z"]          = DeepClone(root["light"]?["z"])!
        };

        return dark;
    }

    private static JsonObject BuildSpecialDark(JsonNode root, (string name, double hue, string bg, string fg, string primary) spec)
    {
        var H = spec.hue.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture);

        // For special themes, dark is the canonical dark palette.
        // Hue is used for color* default/subtle/hover consistency.
        var dark = new JsonObject
        {
            ["bg"] = new JsonObject
            {
                ["default"]    = spec.bg,                                // canonical dark bg
                ["subtle"]     = AdjustL(spec.bg, 0.04),
                ["muted"]      = AdjustL(spec.bg, 0.07),
                ["emphasized"] = AdjustL(spec.bg, 0.11),
                ["overlay"]    = "oklch(0 0 0 / 0.78)",
                ["glass"]      = AdjustA(spec.bg, 0.7)
            },
            ["surface"] = new JsonObject
            {
                ["default"] = AdjustL(spec.bg, 0.04),
                ["raised"]  = AdjustL(spec.bg, 0.08),
                ["overlay"] = AdjustL(spec.bg, 0.12)
            },
            ["fg"] = new JsonObject
            {
                ["default"]   = spec.fg,
                ["subtle"]    = AdjustL(spec.fg, -0.13),
                ["muted"]     = AdjustL(spec.fg, -0.27),
                ["disabled"]  = AdjustL(spec.fg, -0.40),
                ["inverse"]   = spec.bg,
                ["link"]      = AdjustC(spec.primary, 0.05),
                ["linkHover"] = AdjustL(spec.primary, 0.06)
            },
            ["border"] = new JsonObject
            {
                ["default"] = AdjustL(spec.bg, 0.14),
                ["subtle"]  = AdjustL(spec.bg, 0.07),
                ["strong"]  = AdjustL(spec.bg, 0.21),
                ["focus"]   = spec.primary
            },
            ["divider"] = AdjustL(spec.bg, 0.07),
            ["colorPrimary"] = new JsonObject
            {
                ["default"] = spec.primary,
                ["subtle"]  = AdjustL(spec.bg, 0.10, spec.hue, 0.10),
                ["hover"]   = AdjustL(spec.primary, 0.06),
                ["fg"]      = spec.bg
            },
            ["colorSuccess"] = SpecialColor(153),
            ["colorDanger"]  = SpecialColor(19),
            ["colorWarning"] = SpecialColor(75),
            ["colorInfo"]    = SpecialColor(254),
            ["font"] = DeepClone(root["light"]?["font"]) ?? new JsonObject(),
            ["text"]       = DeepClone(root["light"]?["text"])!,
            ["fontWeight"] = DeepClone(root["light"]?["fontWeight"])!,
            ["lineHeight"] = DeepClone(root["light"]?["lineHeight"])!,
            ["shadow"] = new JsonObject
            {
                ["xs"] = "0 1px 2px 0 oklch(0 0 0 / 0.50)",
                ["sm"] = "0 2px 4px -1px oklch(0 0 0 / 0.60)",
                ["md"] = "0 4px 12px -2px oklch(0 0 0 / 0.65)",
                ["lg"] = "0 8px 24px -4px oklch(0 0 0 / 0.70)",
                ["xl"] = "0 16px 48px -8px oklch(0 0 0 / 0.75)"
            },
            ["radius"]     = DeepClone(root["light"]?["radius"])!,
            ["transition"] = DeepClone(root["light"]?["transition"])!,
            ["focusRing"]  = DeepClone(root["light"]?["focusRing"])!,
            ["z"]          = DeepClone(root["light"]?["z"])!
        };

        return dark;
    }

    private static JsonObject SpecialColor(double hue)
    {
        // Generic darker-mode semantic colors at the same hue.
        return new JsonObject
        {
            ["default"] = $"oklch(0.70 0.18 {hue})",
            ["subtle"]  = $"oklch(0.25 0.06 {hue})",
            ["hover"]   = $"oklch(0.76 0.18 {hue})",
            ["fg"]      = $"oklch(0.95 0.005 {hue})"
        };
    }

    private static string AdjustL(string oklch, double deltaL)
    {
        // oklch(L C H[/A]) → oklch(L+deltaL C H)
        var m = System.Text.RegularExpressions.Regex.Match(oklch, @"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)(\s*/\s*[\d.]+)?\s*\)");
        if (!m.Success) return oklch;
        var L = double.Parse(m.Groups[1].Value, System.Globalization.CultureInfo.InvariantCulture) + deltaL;
        var C = m.Groups[2].Value;
        var H = m.Groups[3].Value;
        var A = m.Groups[4].Success ? m.Groups[4].Value : "";
        return FormOklch(L, double.Parse(C, System.Globalization.CultureInfo.InvariantCulture), double.Parse(H, System.Globalization.CultureInfo.InvariantCulture), A);
    }

    private static string AdjustL(string oklch, double deltaL, double injectHue, double injectC)
    {
        var m = System.Text.RegularExpressions.Regex.Match(oklch, @"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)(\s*/\s*[\d.]+)?\s*\)");
        if (!m.Success) return oklch;
        var L = double.Parse(m.Groups[1].Value, System.Globalization.CultureInfo.InvariantCulture) + deltaL;
        return FormOklch(L, injectC, injectHue, "");
    }

    private static string AdjustC(string oklch, double deltaC)
    {
        var m = System.Text.RegularExpressions.Regex.Match(oklch, @"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)");
        if (!m.Success) return oklch;
        var C = double.Parse(m.Groups[2].Value, System.Globalization.CultureInfo.InvariantCulture) + deltaC;
        return FormOklch(double.Parse(m.Groups[1].Value, System.Globalization.CultureInfo.InvariantCulture), C, double.Parse(m.Groups[3].Value, System.Globalization.CultureInfo.InvariantCulture), "");
    }

    private static string FormOklch(double L, double C, double H, string alphaPart)
    {
        var inv = System.Globalization.CultureInfo.InvariantCulture;
        var s = $"oklch({L.ToString("0.###", inv)} {C.ToString("0.###", inv)} {H.ToString("0.##", inv)}{alphaPart})";
        return s;
    }

    private static string AdjustA(string oklch, double alpha)
    {
        var m = System.Text.RegularExpressions.Regex.Match(oklch, @"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)(\s*/\s*[\d.]+)?\s*\)");
        if (!m.Success) return oklch;
        var L = m.Groups[1].Value;
        var C = m.Groups[2].Value;
        var H = m.Groups[3].Value;
        var inv = System.Globalization.CultureInfo.InvariantCulture;
        return $"oklch({L} {C} {H} / {alpha.ToString("0.##", inv)})";
    }

    private static JsonNode? DeepClone(JsonNode? source)
    {
        if (source == null) return null;
        return JsonNode.Parse(source.ToJsonString());
    }
}
